// X3DInterfaceRegistry.cpp
// Auto-generated: the membership tables + lookups.
#include "x3d/nodes/X3DInterfaceRegistry.hpp"

#include "x3d/nodes/X3DNode.hpp"

#include <algorithm>
#include <unordered_map>

namespace x3d::nodes {

namespace {
// Each node-type's transitive interface set, stored contiguously.
const std::unordered_map<std::string, std::vector<InterfaceId>>& table() {
    static const std::unordered_map<std::string, std::vector<InterfaceId>> t = {
        {"AcousticProperties", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode}},
        {"Analyser", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode, InterfaceId::X3DSoundProcessingNode, InterfaceId::X3DTimeDependentNode}},
        {"Anchor", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode, InterfaceId::X3DUrlObject}},
        {"Appearance", {InterfaceId::X3DAppearanceNode, InterfaceId::X3DNode}},
        {"Arc2D", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"ArcClose2D", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"AudioClip", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode, InterfaceId::X3DSoundSourceNode, InterfaceId::X3DTimeDependentNode, InterfaceId::X3DUrlObject}},
        {"AudioDestination", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundDestinationNode, InterfaceId::X3DSoundNode}},
        {"Background", {InterfaceId::X3DBackgroundNode, InterfaceId::X3DBindableNode, InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"BallJoint", {InterfaceId::X3DNode, InterfaceId::X3DRigidJointNode}},
        {"Billboard", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode}},
        {"BiquadFilter", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode, InterfaceId::X3DSoundProcessingNode, InterfaceId::X3DTimeDependentNode}},
        {"BlendedVolumeStyle", {InterfaceId::X3DComposableVolumeRenderStyleNode, InterfaceId::X3DNode, InterfaceId::X3DVolumeRenderStyleNode}},
        {"BooleanFilter", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"BooleanSequencer", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSequencerNode}},
        {"BooleanToggle", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"BooleanTrigger", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DTriggerNode}},
        {"BoundaryEnhancementVolumeStyle", {InterfaceId::X3DComposableVolumeRenderStyleNode, InterfaceId::X3DNode, InterfaceId::X3DVolumeRenderStyleNode}},
        {"BoundedPhysicsModel", {InterfaceId::X3DNode, InterfaceId::X3DParticlePhysicsModelNode}},
        {"Box", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"BufferAudioSource", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode, InterfaceId::X3DSoundSourceNode, InterfaceId::X3DTimeDependentNode, InterfaceId::X3DUrlObject}},
        {"CADAssembly", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode, InterfaceId::X3DProductStructureChildNode}},
        {"CADFace", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DProductStructureChildNode}},
        {"CADLayer", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode}},
        {"CADPart", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode, InterfaceId::X3DProductStructureChildNode}},
        {"CartoonVolumeStyle", {InterfaceId::X3DComposableVolumeRenderStyleNode, InterfaceId::X3DNode, InterfaceId::X3DVolumeRenderStyleNode}},
        {"ChannelMerger", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundChannelNode, InterfaceId::X3DSoundNode}},
        {"ChannelSelector", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundChannelNode, InterfaceId::X3DSoundNode}},
        {"ChannelSplitter", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundChannelNode, InterfaceId::X3DSoundNode}},
        {"Circle2D", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"ClipPlane", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"CollidableOffset", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNBodyCollidableNode, InterfaceId::X3DNode}},
        {"CollidableShape", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNBodyCollidableNode, InterfaceId::X3DNode}},
        {"Collision", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode}},
        {"CollisionCollection", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"CollisionSensor", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode}},
        {"CollisionSpace", {InterfaceId::X3DBoundedObject, InterfaceId::X3DNBodyCollisionSpaceNode, InterfaceId::X3DNode}},
        {"Color", {InterfaceId::X3DColorNode, InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode}},
        {"ColorChaser", {InterfaceId::X3DChaserNode, InterfaceId::X3DChildNode, InterfaceId::X3DFollowerNode, InterfaceId::X3DNode}},
        {"ColorDamper", {InterfaceId::X3DChildNode, InterfaceId::X3DDamperNode, InterfaceId::X3DFollowerNode, InterfaceId::X3DNode}},
        {"ColorInterpolator", {InterfaceId::X3DChildNode, InterfaceId::X3DInterpolatorNode, InterfaceId::X3DNode}},
        {"ColorRGBA", {InterfaceId::X3DColorNode, InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode}},
        {"ComposedCubeMapTexture", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DEnvironmentTextureNode, InterfaceId::X3DNode, InterfaceId::X3DTextureNode}},
        {"ComposedShader", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode, InterfaceId::X3DProgrammableShaderObject, InterfaceId::X3DShaderNode}},
        {"ComposedTexture3D", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode, InterfaceId::X3DTexture3DNode, InterfaceId::X3DTextureNode}},
        {"ComposedVolumeStyle", {InterfaceId::X3DComposableVolumeRenderStyleNode, InterfaceId::X3DNode, InterfaceId::X3DVolumeRenderStyleNode}},
        {"Cone", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"ConeEmitter", {InterfaceId::X3DNode, InterfaceId::X3DParticleEmitterNode}},
        {"Contact", {InterfaceId::X3DNode}},
        {"Contour2D", {InterfaceId::X3DNode}},
        {"ContourPolyline2D", {InterfaceId::X3DNode, InterfaceId::X3DNurbsControlCurveNode}},
        {"Convolver", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode, InterfaceId::X3DSoundProcessingNode, InterfaceId::X3DTimeDependentNode}},
        {"Coordinate", {InterfaceId::X3DCoordinateNode, InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode}},
        {"CoordinateChaser", {InterfaceId::X3DChaserNode, InterfaceId::X3DChildNode, InterfaceId::X3DFollowerNode, InterfaceId::X3DNode}},
        {"CoordinateDamper", {InterfaceId::X3DChildNode, InterfaceId::X3DDamperNode, InterfaceId::X3DFollowerNode, InterfaceId::X3DNode}},
        {"CoordinateDouble", {InterfaceId::X3DCoordinateNode, InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode}},
        {"CoordinateInterpolator", {InterfaceId::X3DChildNode, InterfaceId::X3DInterpolatorNode, InterfaceId::X3DNode}},
        {"CoordinateInterpolator2D", {InterfaceId::X3DChildNode, InterfaceId::X3DInterpolatorNode, InterfaceId::X3DNode}},
        {"Cylinder", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"CylinderSensor", {InterfaceId::X3DChildNode, InterfaceId::X3DDragSensorNode, InterfaceId::X3DNode, InterfaceId::X3DPointingDeviceSensorNode, InterfaceId::X3DSensorNode}},
        {"DISEntityManager", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"DISEntityTypeMapping", {InterfaceId::X3DChildNode, InterfaceId::X3DInfoNode, InterfaceId::X3DNode, InterfaceId::X3DUrlObject}},
        {"Delay", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode, InterfaceId::X3DSoundProcessingNode, InterfaceId::X3DTimeDependentNode}},
        {"DirectionalLight", {InterfaceId::X3DChildNode, InterfaceId::X3DLightNode, InterfaceId::X3DNode}},
        {"Disk2D", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"DoubleAxisHingeJoint", {InterfaceId::X3DNode, InterfaceId::X3DRigidJointNode}},
        {"DynamicsCompressor", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode, InterfaceId::X3DSoundProcessingNode, InterfaceId::X3DTimeDependentNode}},
        {"EaseInEaseOut", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"EdgeEnhancementVolumeStyle", {InterfaceId::X3DComposableVolumeRenderStyleNode, InterfaceId::X3DNode, InterfaceId::X3DVolumeRenderStyleNode}},
        {"ElevationGrid", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"EspduTransform", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNetworkSensorNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode}},
        {"ExplosionEmitter", {InterfaceId::X3DNode, InterfaceId::X3DParticleEmitterNode}},
        {"Extrusion", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"FillProperties", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode}},
        {"FloatVertexAttribute", {InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode, InterfaceId::X3DVertexAttributeNode}},
        {"Fog", {InterfaceId::X3DBindableNode, InterfaceId::X3DChildNode, InterfaceId::X3DFogObject, InterfaceId::X3DNode}},
        {"FogCoordinate", {InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode}},
        {"FontStyle", {InterfaceId::X3DFontStyleNode, InterfaceId::X3DNode}},
        {"ForcePhysicsModel", {InterfaceId::X3DNode, InterfaceId::X3DParticlePhysicsModelNode}},
        {"Gain", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode, InterfaceId::X3DSoundProcessingNode, InterfaceId::X3DTimeDependentNode}},
        {"GeneratedCubeMapTexture", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DEnvironmentTextureNode, InterfaceId::X3DNode, InterfaceId::X3DTextureNode}},
        {"GeoCoordinate", {InterfaceId::X3DCoordinateNode, InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode}},
        {"GeoElevationGrid", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"GeoLOD", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"GeoLocation", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode}},
        {"GeoMetadata", {InterfaceId::X3DChildNode, InterfaceId::X3DInfoNode, InterfaceId::X3DNode, InterfaceId::X3DUrlObject}},
        {"GeoOrigin", {InterfaceId::X3DNode}},
        {"GeoPositionInterpolator", {InterfaceId::X3DChildNode, InterfaceId::X3DInterpolatorNode, InterfaceId::X3DNode}},
        {"GeoProximitySensor", {InterfaceId::X3DChildNode, InterfaceId::X3DEnvironmentalSensorNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode}},
        {"GeoTouchSensor", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DPointingDeviceSensorNode, InterfaceId::X3DSensorNode, InterfaceId::X3DTouchSensorNode}},
        {"GeoTransform", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode}},
        {"GeoViewpoint", {InterfaceId::X3DBindableNode, InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DViewpointNode}},
        {"Group", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode}},
        {"HAnimDisplacer", {InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode}},
        {"HAnimHumanoid", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"HAnimJoint", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"HAnimMotion", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"HAnimSegment", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode}},
        {"HAnimSite", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode}},
        {"ImageCubeMapTexture", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DEnvironmentTextureNode, InterfaceId::X3DNode, InterfaceId::X3DTextureNode, InterfaceId::X3DUrlObject}},
        {"ImageTexture", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode, InterfaceId::X3DSingleTextureNode, InterfaceId::X3DTexture2DNode, InterfaceId::X3DTextureNode, InterfaceId::X3DUrlObject}},
        {"ImageTexture3D", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode, InterfaceId::X3DTexture3DNode, InterfaceId::X3DTextureNode, InterfaceId::X3DUrlObject}},
        {"IndexedFaceSet", {InterfaceId::X3DComposedGeometryNode, InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"IndexedLineSet", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"IndexedQuadSet", {InterfaceId::X3DComposedGeometryNode, InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"IndexedTriangleFanSet", {InterfaceId::X3DComposedGeometryNode, InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"IndexedTriangleSet", {InterfaceId::X3DComposedGeometryNode, InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"IndexedTriangleStripSet", {InterfaceId::X3DComposedGeometryNode, InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"Inline", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DUrlObject}},
        {"IntegerSequencer", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSequencerNode}},
        {"IntegerTrigger", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DTriggerNode}},
        {"IsoSurfaceVolumeData", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DVolumeDataNode}},
        {"KeySensor", {InterfaceId::X3DChildNode, InterfaceId::X3DKeyDeviceSensorNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode}},
        {"LOD", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode}},
        {"Layer", {InterfaceId::X3DLayerNode, InterfaceId::X3DNode, InterfaceId::X3DPickableObject}},
        {"LayerSet", {InterfaceId::X3DNode}},
        {"Layout", {InterfaceId::X3DChildNode, InterfaceId::X3DLayoutNode, InterfaceId::X3DNode}},
        {"LayoutGroup", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode}},
        {"LayoutLayer", {InterfaceId::X3DLayerNode, InterfaceId::X3DNode, InterfaceId::X3DPickableObject}},
        {"LinePickSensor", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DPickSensorNode, InterfaceId::X3DSensorNode}},
        {"LineProperties", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode}},
        {"LineSet", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"ListenerPointSource", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode, InterfaceId::X3DSoundSourceNode, InterfaceId::X3DTimeDependentNode}},
        {"LoadSensor", {InterfaceId::X3DChildNode, InterfaceId::X3DNetworkSensorNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode}},
        {"LocalFog", {InterfaceId::X3DChildNode, InterfaceId::X3DFogObject, InterfaceId::X3DNode}},
        {"Material", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DMaterialNode, InterfaceId::X3DNode, InterfaceId::X3DOneSidedMaterialNode}},
        {"Matrix3VertexAttribute", {InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode, InterfaceId::X3DVertexAttributeNode}},
        {"Matrix4VertexAttribute", {InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode, InterfaceId::X3DVertexAttributeNode}},
        {"MetadataBoolean", {InterfaceId::X3DMetadataObject, InterfaceId::X3DNode}},
        {"MetadataDouble", {InterfaceId::X3DMetadataObject, InterfaceId::X3DNode}},
        {"MetadataFloat", {InterfaceId::X3DMetadataObject, InterfaceId::X3DNode}},
        {"MetadataInteger", {InterfaceId::X3DMetadataObject, InterfaceId::X3DNode}},
        {"MetadataSet", {InterfaceId::X3DMetadataObject, InterfaceId::X3DNode}},
        {"MetadataString", {InterfaceId::X3DMetadataObject, InterfaceId::X3DNode}},
        {"MicrophoneSource", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode, InterfaceId::X3DSoundSourceNode, InterfaceId::X3DTimeDependentNode}},
        {"MotorJoint", {InterfaceId::X3DNode, InterfaceId::X3DRigidJointNode}},
        {"MovieTexture", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSingleTextureNode, InterfaceId::X3DSoundNode, InterfaceId::X3DSoundSourceNode, InterfaceId::X3DTexture2DNode, InterfaceId::X3DTextureNode, InterfaceId::X3DTimeDependentNode, InterfaceId::X3DUrlObject}},
        {"MultiTexture", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode, InterfaceId::X3DTextureNode}},
        {"MultiTextureCoordinate", {InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode, InterfaceId::X3DTextureCoordinateNode}},
        {"MultiTextureTransform", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode, InterfaceId::X3DTextureTransformNode}},
        {"NavigationInfo", {InterfaceId::X3DBindableNode, InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"Normal", {InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode, InterfaceId::X3DNormalNode}},
        {"NormalInterpolator", {InterfaceId::X3DChildNode, InterfaceId::X3DInterpolatorNode, InterfaceId::X3DNode}},
        {"NurbsCurve", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode, InterfaceId::X3DParametricGeometryNode}},
        {"NurbsCurve2D", {InterfaceId::X3DNode, InterfaceId::X3DNurbsControlCurveNode}},
        {"NurbsOrientationInterpolator", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"NurbsPatchSurface", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode, InterfaceId::X3DNurbsSurfaceGeometryNode, InterfaceId::X3DParametricGeometryNode}},
        {"NurbsPositionInterpolator", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"NurbsSet", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"NurbsSurfaceInterpolator", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"NurbsSweptSurface", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode, InterfaceId::X3DParametricGeometryNode}},
        {"NurbsSwungSurface", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode, InterfaceId::X3DParametricGeometryNode}},
        {"NurbsTextureCoordinate", {InterfaceId::X3DNode}},
        {"NurbsTrimmedSurface", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode, InterfaceId::X3DNurbsSurfaceGeometryNode, InterfaceId::X3DParametricGeometryNode}},
        {"OpacityMapVolumeStyle", {InterfaceId::X3DComposableVolumeRenderStyleNode, InterfaceId::X3DNode, InterfaceId::X3DVolumeRenderStyleNode}},
        {"OrientationChaser", {InterfaceId::X3DChaserNode, InterfaceId::X3DChildNode, InterfaceId::X3DFollowerNode, InterfaceId::X3DNode}},
        {"OrientationDamper", {InterfaceId::X3DChildNode, InterfaceId::X3DDamperNode, InterfaceId::X3DFollowerNode, InterfaceId::X3DNode}},
        {"OrientationInterpolator", {InterfaceId::X3DChildNode, InterfaceId::X3DInterpolatorNode, InterfaceId::X3DNode}},
        {"OrthoViewpoint", {InterfaceId::X3DBindableNode, InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DViewpointNode}},
        {"OscillatorSource", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode, InterfaceId::X3DSoundSourceNode, InterfaceId::X3DTimeDependentNode}},
        {"PackagedShader", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode, InterfaceId::X3DProgrammableShaderObject, InterfaceId::X3DShaderNode, InterfaceId::X3DUrlObject}},
        {"ParticleSystem", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DShapeNode}},
        {"PeriodicWave", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode}},
        {"PhysicalMaterial", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DMaterialNode, InterfaceId::X3DNode, InterfaceId::X3DOneSidedMaterialNode}},
        {"PickableGroup", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode, InterfaceId::X3DPickableObject}},
        {"PixelTexture", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode, InterfaceId::X3DSingleTextureNode, InterfaceId::X3DTexture2DNode, InterfaceId::X3DTextureNode}},
        {"PixelTexture3D", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode, InterfaceId::X3DTexture3DNode, InterfaceId::X3DTextureNode}},
        {"PlaneSensor", {InterfaceId::X3DChildNode, InterfaceId::X3DDragSensorNode, InterfaceId::X3DNode, InterfaceId::X3DPointingDeviceSensorNode, InterfaceId::X3DSensorNode}},
        {"PointEmitter", {InterfaceId::X3DNode, InterfaceId::X3DParticleEmitterNode}},
        {"PointLight", {InterfaceId::X3DChildNode, InterfaceId::X3DLightNode, InterfaceId::X3DNode}},
        {"PointPickSensor", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DPickSensorNode, InterfaceId::X3DSensorNode}},
        {"PointProperties", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode}},
        {"PointSet", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"Polyline2D", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"PolylineEmitter", {InterfaceId::X3DNode, InterfaceId::X3DParticleEmitterNode}},
        {"Polypoint2D", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"PositionChaser", {InterfaceId::X3DChaserNode, InterfaceId::X3DChildNode, InterfaceId::X3DFollowerNode, InterfaceId::X3DNode}},
        {"PositionChaser2D", {InterfaceId::X3DChaserNode, InterfaceId::X3DChildNode, InterfaceId::X3DFollowerNode, InterfaceId::X3DNode}},
        {"PositionDamper", {InterfaceId::X3DChildNode, InterfaceId::X3DDamperNode, InterfaceId::X3DFollowerNode, InterfaceId::X3DNode}},
        {"PositionDamper2D", {InterfaceId::X3DChildNode, InterfaceId::X3DDamperNode, InterfaceId::X3DFollowerNode, InterfaceId::X3DNode}},
        {"PositionInterpolator", {InterfaceId::X3DChildNode, InterfaceId::X3DInterpolatorNode, InterfaceId::X3DNode}},
        {"PositionInterpolator2D", {InterfaceId::X3DChildNode, InterfaceId::X3DInterpolatorNode, InterfaceId::X3DNode}},
        {"PrimitivePickSensor", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DPickSensorNode, InterfaceId::X3DSensorNode}},
        {"ProgramShader", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode, InterfaceId::X3DShaderNode}},
        {"ProjectionVolumeStyle", {InterfaceId::X3DNode, InterfaceId::X3DVolumeRenderStyleNode}},
        {"ProtoInstance", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DPrototypeInstance}},
        {"ProximitySensor", {InterfaceId::X3DChildNode, InterfaceId::X3DEnvironmentalSensorNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode}},
        {"QuadSet", {InterfaceId::X3DComposedGeometryNode, InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"ReceiverPdu", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNetworkSensorNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode}},
        {"Rectangle2D", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"RigidBody", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"RigidBodyCollection", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"ScalarChaser", {InterfaceId::X3DChaserNode, InterfaceId::X3DChildNode, InterfaceId::X3DFollowerNode, InterfaceId::X3DNode}},
        {"ScalarDamper", {InterfaceId::X3DChildNode, InterfaceId::X3DDamperNode, InterfaceId::X3DFollowerNode, InterfaceId::X3DNode}},
        {"ScalarInterpolator", {InterfaceId::X3DChildNode, InterfaceId::X3DInterpolatorNode, InterfaceId::X3DNode}},
        {"ScreenFontStyle", {InterfaceId::X3DFontStyleNode, InterfaceId::X3DNode}},
        {"ScreenGroup", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode}},
        {"Script", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DScriptNode, InterfaceId::X3DUrlObject}},
        {"SegmentedVolumeData", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DVolumeDataNode}},
        {"ShadedVolumeStyle", {InterfaceId::X3DComposableVolumeRenderStyleNode, InterfaceId::X3DNode, InterfaceId::X3DVolumeRenderStyleNode}},
        {"ShaderPart", {InterfaceId::X3DNode, InterfaceId::X3DUrlObject}},
        {"ShaderProgram", {InterfaceId::X3DNode, InterfaceId::X3DProgrammableShaderObject, InterfaceId::X3DUrlObject}},
        {"Shape", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DShapeNode}},
        {"SignalPdu", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNetworkSensorNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode}},
        {"SilhouetteEnhancementVolumeStyle", {InterfaceId::X3DComposableVolumeRenderStyleNode, InterfaceId::X3DNode, InterfaceId::X3DVolumeRenderStyleNode}},
        {"SingleAxisHingeJoint", {InterfaceId::X3DNode, InterfaceId::X3DRigidJointNode}},
        {"SliderJoint", {InterfaceId::X3DNode, InterfaceId::X3DRigidJointNode}},
        {"Sound", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode}},
        {"SpatialSound", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode}},
        {"Sphere", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"SphereSensor", {InterfaceId::X3DChildNode, InterfaceId::X3DDragSensorNode, InterfaceId::X3DNode, InterfaceId::X3DPointingDeviceSensorNode, InterfaceId::X3DSensorNode}},
        {"SplinePositionInterpolator", {InterfaceId::X3DChildNode, InterfaceId::X3DInterpolatorNode, InterfaceId::X3DNode}},
        {"SplinePositionInterpolator2D", {InterfaceId::X3DChildNode, InterfaceId::X3DInterpolatorNode, InterfaceId::X3DNode}},
        {"SplineScalarInterpolator", {InterfaceId::X3DChildNode, InterfaceId::X3DInterpolatorNode, InterfaceId::X3DNode}},
        {"SpotLight", {InterfaceId::X3DChildNode, InterfaceId::X3DLightNode, InterfaceId::X3DNode}},
        {"SquadOrientationInterpolator", {InterfaceId::X3DChildNode, InterfaceId::X3DInterpolatorNode, InterfaceId::X3DNode}},
        {"StaticGroup", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"StreamAudioDestination", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundDestinationNode, InterfaceId::X3DSoundNode}},
        {"StreamAudioSource", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode, InterfaceId::X3DSoundSourceNode, InterfaceId::X3DTimeDependentNode}},
        {"StringSensor", {InterfaceId::X3DChildNode, InterfaceId::X3DKeyDeviceSensorNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode}},
        {"SurfaceEmitter", {InterfaceId::X3DNode, InterfaceId::X3DParticleEmitterNode}},
        {"Switch", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode}},
        {"TexCoordChaser2D", {InterfaceId::X3DChaserNode, InterfaceId::X3DChildNode, InterfaceId::X3DFollowerNode, InterfaceId::X3DNode}},
        {"TexCoordDamper2D", {InterfaceId::X3DChildNode, InterfaceId::X3DDamperNode, InterfaceId::X3DFollowerNode, InterfaceId::X3DNode}},
        {"Text", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"TextureBackground", {InterfaceId::X3DBackgroundNode, InterfaceId::X3DBindableNode, InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"TextureCoordinate", {InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode, InterfaceId::X3DSingleTextureCoordinateNode, InterfaceId::X3DTextureCoordinateNode}},
        {"TextureCoordinate3D", {InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode, InterfaceId::X3DSingleTextureCoordinateNode, InterfaceId::X3DTextureCoordinateNode}},
        {"TextureCoordinate4D", {InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode, InterfaceId::X3DSingleTextureCoordinateNode, InterfaceId::X3DTextureCoordinateNode}},
        {"TextureCoordinateGenerator", {InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode, InterfaceId::X3DSingleTextureCoordinateNode, InterfaceId::X3DTextureCoordinateNode}},
        {"TextureProjector", {InterfaceId::X3DChildNode, InterfaceId::X3DLightNode, InterfaceId::X3DNode, InterfaceId::X3DTextureProjectorNode}},
        {"TextureProjectorParallel", {InterfaceId::X3DChildNode, InterfaceId::X3DLightNode, InterfaceId::X3DNode, InterfaceId::X3DTextureProjectorNode}},
        {"TextureProperties", {InterfaceId::X3DNode}},
        {"TextureTransform", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode, InterfaceId::X3DTextureTransformNode}},
        {"TextureTransform3D", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode, InterfaceId::X3DTextureTransformNode}},
        {"TextureTransformMatrix3D", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode, InterfaceId::X3DTextureTransformNode}},
        {"TimeSensor", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode, InterfaceId::X3DTimeDependentNode}},
        {"TimeTrigger", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DTriggerNode}},
        {"ToneMappedVolumeStyle", {InterfaceId::X3DComposableVolumeRenderStyleNode, InterfaceId::X3DNode, InterfaceId::X3DVolumeRenderStyleNode}},
        {"TouchSensor", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DPointingDeviceSensorNode, InterfaceId::X3DSensorNode, InterfaceId::X3DTouchSensorNode}},
        {"Transform", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode}},
        {"TransformSensor", {InterfaceId::X3DChildNode, InterfaceId::X3DEnvironmentalSensorNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode}},
        {"TransmitterPdu", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNetworkSensorNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode}},
        {"TriangleFanSet", {InterfaceId::X3DComposedGeometryNode, InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"TriangleSet", {InterfaceId::X3DComposedGeometryNode, InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"TriangleSet2D", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"TriangleStripSet", {InterfaceId::X3DComposedGeometryNode, InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"TwoSidedMaterial", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DMaterialNode, InterfaceId::X3DNode}},
        {"UniversalJoint", {InterfaceId::X3DNode, InterfaceId::X3DRigidJointNode}},
        {"UnlitMaterial", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DMaterialNode, InterfaceId::X3DNode, InterfaceId::X3DOneSidedMaterialNode}},
        {"Viewpoint", {InterfaceId::X3DBindableNode, InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DViewpointNode}},
        {"ViewpointGroup", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"Viewport", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode, InterfaceId::X3DViewportNode}},
        {"VisibilitySensor", {InterfaceId::X3DChildNode, InterfaceId::X3DEnvironmentalSensorNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode}},
        {"VolumeData", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DVolumeDataNode}},
        {"VolumeEmitter", {InterfaceId::X3DNode, InterfaceId::X3DParticleEmitterNode}},
        {"VolumePickSensor", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DPickSensorNode, InterfaceId::X3DSensorNode}},
        {"WaveShaper", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode, InterfaceId::X3DSoundProcessingNode, InterfaceId::X3DTimeDependentNode}},
        {"WindPhysicsModel", {InterfaceId::X3DNode, InterfaceId::X3DParticlePhysicsModelNode}},
        {"WorldInfo", {InterfaceId::X3DChildNode, InterfaceId::X3DInfoNode, InterfaceId::X3DNode}},
        {"X3DAppearanceChildNode", {InterfaceId::X3DNode}},
        {"X3DAppearanceNode", {InterfaceId::X3DNode}},
        {"X3DArrayField", {}},
        {"X3DBackgroundNode", {InterfaceId::X3DBindableNode, InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"X3DBindableNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"X3DBoundedObject", {}},
        {"X3DChaserNode", {InterfaceId::X3DChildNode, InterfaceId::X3DFollowerNode, InterfaceId::X3DNode}},
        {"X3DChildNode", {InterfaceId::X3DNode}},
        {"X3DColorNode", {InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode}},
        {"X3DComposableVolumeRenderStyleNode", {InterfaceId::X3DNode, InterfaceId::X3DVolumeRenderStyleNode}},
        {"X3DComposedGeometryNode", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"X3DCoordinateNode", {InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode}},
        {"X3DDamperNode", {InterfaceId::X3DChildNode, InterfaceId::X3DFollowerNode, InterfaceId::X3DNode}},
        {"X3DDragSensorNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DPointingDeviceSensorNode, InterfaceId::X3DSensorNode}},
        {"X3DEnvironmentTextureNode", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode, InterfaceId::X3DTextureNode}},
        {"X3DEnvironmentalSensorNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode}},
        {"X3DField", {}},
        {"X3DFogObject", {}},
        {"X3DFollowerNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"X3DFontStyleNode", {InterfaceId::X3DNode}},
        {"X3DGeometricPropertyNode", {InterfaceId::X3DNode}},
        {"X3DGeometryNode", {InterfaceId::X3DNode}},
        {"X3DGroupingNode", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"X3DInfoNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"X3DInterpolatorNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"X3DKeyDeviceSensorNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode}},
        {"X3DLayerNode", {InterfaceId::X3DNode, InterfaceId::X3DPickableObject}},
        {"X3DLayoutNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"X3DLightNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"X3DMaterialNode", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode}},
        {"X3DMetadataObject", {}},
        {"X3DNBodyCollidableNode", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"X3DNBodyCollisionSpaceNode", {InterfaceId::X3DBoundedObject, InterfaceId::X3DNode}},
        {"X3DNetworkSensorNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode}},
        {"X3DNode", {}},
        {"X3DNormalNode", {InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode}},
        {"X3DNurbsControlCurveNode", {InterfaceId::X3DNode}},
        {"X3DNurbsSurfaceGeometryNode", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode, InterfaceId::X3DParametricGeometryNode}},
        {"X3DOneSidedMaterialNode", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DMaterialNode, InterfaceId::X3DNode}},
        {"X3DParametricGeometryNode", {InterfaceId::X3DGeometryNode, InterfaceId::X3DNode}},
        {"X3DParticleEmitterNode", {InterfaceId::X3DNode}},
        {"X3DParticlePhysicsModelNode", {InterfaceId::X3DNode}},
        {"X3DPickSensorNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode}},
        {"X3DPickableObject", {}},
        {"X3DPointingDeviceSensorNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSensorNode}},
        {"X3DProductStructureChildNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"X3DProgrammableShaderObject", {}},
        {"X3DPrototypeInstance", {InterfaceId::X3DNode}},
        {"X3DRigidJointNode", {InterfaceId::X3DNode}},
        {"X3DScriptNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DUrlObject}},
        {"X3DSensorNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"X3DSequencerNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"X3DShaderNode", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode}},
        {"X3DShapeNode", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"X3DSingleTextureCoordinateNode", {InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode, InterfaceId::X3DTextureCoordinateNode}},
        {"X3DSingleTextureNode", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode, InterfaceId::X3DTextureNode}},
        {"X3DSingleTextureTransformNode", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode, InterfaceId::X3DTextureTransformNode}},
        {"X3DSoundChannelNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode}},
        {"X3DSoundDestinationNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode}},
        {"X3DSoundNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"X3DSoundProcessingNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode, InterfaceId::X3DTimeDependentNode}},
        {"X3DSoundSourceNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DSoundNode, InterfaceId::X3DTimeDependentNode}},
        {"X3DStatement", {}},
        {"X3DTexture2DNode", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode, InterfaceId::X3DSingleTextureNode, InterfaceId::X3DTextureNode}},
        {"X3DTexture3DNode", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode, InterfaceId::X3DTextureNode}},
        {"X3DTextureCoordinateNode", {InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode}},
        {"X3DTextureNode", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode}},
        {"X3DTextureProjectorNode", {InterfaceId::X3DChildNode, InterfaceId::X3DLightNode, InterfaceId::X3DNode}},
        {"X3DTextureTransformNode", {InterfaceId::X3DAppearanceChildNode, InterfaceId::X3DNode}},
        {"X3DTimeDependentNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"X3DTouchSensorNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode, InterfaceId::X3DPointingDeviceSensorNode, InterfaceId::X3DSensorNode}},
        {"X3DTriggerNode", {InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"X3DUrlObject", {}},
        {"X3DVertexAttributeNode", {InterfaceId::X3DGeometricPropertyNode, InterfaceId::X3DNode}},
        {"X3DViewpointNode", {InterfaceId::X3DBindableNode, InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"X3DViewportNode", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DGroupingNode, InterfaceId::X3DNode}},
        {"X3DVolumeDataNode", {InterfaceId::X3DBoundedObject, InterfaceId::X3DChildNode, InterfaceId::X3DNode}},
        {"X3DVolumeRenderStyleNode", {InterfaceId::X3DNode}},
    };
    return t;
}
}  // namespace

std::span<const InterfaceId>
X3DInterfaceRegistry::interfacesOf(const std::string& nodeTypeName) {
    static const std::vector<InterfaceId> empty;
    auto it = table().find(nodeTypeName);
    return it == table().end() ? std::span<const InterfaceId>(empty)
                              : std::span<const InterfaceId>(it->second);
}

bool X3DInterfaceRegistry::nodeImplements(const std::string& nodeTypeName,
                                          InterfaceId iface) {
    for (InterfaceId i : interfacesOf(nodeTypeName))
        if (i == iface) return true;
    return false;
}

bool X3DInterfaceRegistry::nodeImplements(const X3DNode* node, InterfaceId iface) {
    return node && nodeImplements(node->nodeTypeName(), iface);
}

const std::vector<std::string>&
X3DInterfaceRegistry::nodesImplementing(InterfaceId iface) {
    static std::unordered_map<InterfaceId, std::vector<std::string>> cache;
    auto it = cache.find(iface);
    if (it != cache.end()) return it->second;
    std::vector<std::string> out;
    for (const auto& [name, ifaces] : table())
        for (InterfaceId i : ifaces)
            if (i == iface) { out.push_back(name); break; }
    std::sort(out.begin(), out.end());
    return cache.emplace(iface, std::move(out)).first->second;
}

} // namespace x3d::nodes
