// X3DNodeFactory.cpp
// Auto-generated: the registry definition (compiled once into the node lib).
#include "x3d/nodes/X3DNodeFactory.hpp"

namespace x3d::nodes {

namespace factory_detail {
std::shared_ptr<X3DNode> createAcousticProperties();
std::shared_ptr<X3DNode> createAnalyser();
std::shared_ptr<X3DNode> createAnchor();
std::shared_ptr<X3DNode> createAppearance();
std::shared_ptr<X3DNode> createArc2D();
std::shared_ptr<X3DNode> createArcClose2D();
std::shared_ptr<X3DNode> createAudioClip();
std::shared_ptr<X3DNode> createAudioDestination();
std::shared_ptr<X3DNode> createBackground();
std::shared_ptr<X3DNode> createBallJoint();
std::shared_ptr<X3DNode> createBillboard();
std::shared_ptr<X3DNode> createBiquadFilter();
std::shared_ptr<X3DNode> createBlendedVolumeStyle();
std::shared_ptr<X3DNode> createBooleanFilter();
std::shared_ptr<X3DNode> createBooleanSequencer();
std::shared_ptr<X3DNode> createBooleanToggle();
std::shared_ptr<X3DNode> createBooleanTrigger();
std::shared_ptr<X3DNode> createBoundaryEnhancementVolumeStyle();
std::shared_ptr<X3DNode> createBoundedPhysicsModel();
std::shared_ptr<X3DNode> createBox();
std::shared_ptr<X3DNode> createBufferAudioSource();
std::shared_ptr<X3DNode> createCADAssembly();
std::shared_ptr<X3DNode> createCADFace();
std::shared_ptr<X3DNode> createCADLayer();
std::shared_ptr<X3DNode> createCADPart();
std::shared_ptr<X3DNode> createCartoonVolumeStyle();
std::shared_ptr<X3DNode> createChannelMerger();
std::shared_ptr<X3DNode> createChannelSelector();
std::shared_ptr<X3DNode> createChannelSplitter();
std::shared_ptr<X3DNode> createCircle2D();
std::shared_ptr<X3DNode> createClipPlane();
std::shared_ptr<X3DNode> createCollidableOffset();
std::shared_ptr<X3DNode> createCollidableShape();
std::shared_ptr<X3DNode> createCollision();
std::shared_ptr<X3DNode> createCollisionCollection();
std::shared_ptr<X3DNode> createCollisionSensor();
std::shared_ptr<X3DNode> createCollisionSpace();
std::shared_ptr<X3DNode> createColor();
std::shared_ptr<X3DNode> createColorChaser();
std::shared_ptr<X3DNode> createColorDamper();
std::shared_ptr<X3DNode> createColorInterpolator();
std::shared_ptr<X3DNode> createColorRGBA();
std::shared_ptr<X3DNode> createComposedCubeMapTexture();
std::shared_ptr<X3DNode> createComposedShader();
std::shared_ptr<X3DNode> createComposedTexture3D();
std::shared_ptr<X3DNode> createComposedVolumeStyle();
std::shared_ptr<X3DNode> createCone();
std::shared_ptr<X3DNode> createConeEmitter();
std::shared_ptr<X3DNode> createContact();
std::shared_ptr<X3DNode> createContour2D();
std::shared_ptr<X3DNode> createContourPolyline2D();
std::shared_ptr<X3DNode> createConvolver();
std::shared_ptr<X3DNode> createCoordinate();
std::shared_ptr<X3DNode> createCoordinateChaser();
std::shared_ptr<X3DNode> createCoordinateDamper();
std::shared_ptr<X3DNode> createCoordinateDouble();
std::shared_ptr<X3DNode> createCoordinateInterpolator();
std::shared_ptr<X3DNode> createCoordinateInterpolator2D();
std::shared_ptr<X3DNode> createCylinder();
std::shared_ptr<X3DNode> createCylinderSensor();
std::shared_ptr<X3DNode> createDISEntityManager();
std::shared_ptr<X3DNode> createDISEntityTypeMapping();
std::shared_ptr<X3DNode> createDelay();
std::shared_ptr<X3DNode> createDirectionalLight();
std::shared_ptr<X3DNode> createDisk2D();
std::shared_ptr<X3DNode> createDoubleAxisHingeJoint();
std::shared_ptr<X3DNode> createDynamicsCompressor();
std::shared_ptr<X3DNode> createEaseInEaseOut();
std::shared_ptr<X3DNode> createEdgeEnhancementVolumeStyle();
std::shared_ptr<X3DNode> createElevationGrid();
std::shared_ptr<X3DNode> createEspduTransform();
std::shared_ptr<X3DNode> createExplosionEmitter();
std::shared_ptr<X3DNode> createExtrusion();
std::shared_ptr<X3DNode> createFillProperties();
std::shared_ptr<X3DNode> createFloatVertexAttribute();
std::shared_ptr<X3DNode> createFog();
std::shared_ptr<X3DNode> createFogCoordinate();
std::shared_ptr<X3DNode> createFontStyle();
std::shared_ptr<X3DNode> createForcePhysicsModel();
std::shared_ptr<X3DNode> createGain();
std::shared_ptr<X3DNode> createGeneratedCubeMapTexture();
std::shared_ptr<X3DNode> createGeoCoordinate();
std::shared_ptr<X3DNode> createGeoElevationGrid();
std::shared_ptr<X3DNode> createGeoLOD();
std::shared_ptr<X3DNode> createGeoLocation();
std::shared_ptr<X3DNode> createGeoMetadata();
std::shared_ptr<X3DNode> createGeoOrigin();
std::shared_ptr<X3DNode> createGeoPositionInterpolator();
std::shared_ptr<X3DNode> createGeoProximitySensor();
std::shared_ptr<X3DNode> createGeoTouchSensor();
std::shared_ptr<X3DNode> createGeoTransform();
std::shared_ptr<X3DNode> createGeoViewpoint();
std::shared_ptr<X3DNode> createGroup();
std::shared_ptr<X3DNode> createHAnimDisplacer();
std::shared_ptr<X3DNode> createHAnimHumanoid();
std::shared_ptr<X3DNode> createHAnimJoint();
std::shared_ptr<X3DNode> createHAnimMotion();
std::shared_ptr<X3DNode> createHAnimSegment();
std::shared_ptr<X3DNode> createHAnimSite();
std::shared_ptr<X3DNode> createImageCubeMapTexture();
std::shared_ptr<X3DNode> createImageTexture();
std::shared_ptr<X3DNode> createImageTexture3D();
std::shared_ptr<X3DNode> createIndexedFaceSet();
std::shared_ptr<X3DNode> createIndexedLineSet();
std::shared_ptr<X3DNode> createIndexedQuadSet();
std::shared_ptr<X3DNode> createIndexedTriangleFanSet();
std::shared_ptr<X3DNode> createIndexedTriangleSet();
std::shared_ptr<X3DNode> createIndexedTriangleStripSet();
std::shared_ptr<X3DNode> createInline();
std::shared_ptr<X3DNode> createIntegerSequencer();
std::shared_ptr<X3DNode> createIntegerTrigger();
std::shared_ptr<X3DNode> createIsoSurfaceVolumeData();
std::shared_ptr<X3DNode> createKeySensor();
std::shared_ptr<X3DNode> createLOD();
std::shared_ptr<X3DNode> createLayer();
std::shared_ptr<X3DNode> createLayerSet();
std::shared_ptr<X3DNode> createLayout();
std::shared_ptr<X3DNode> createLayoutGroup();
std::shared_ptr<X3DNode> createLayoutLayer();
std::shared_ptr<X3DNode> createLinePickSensor();
std::shared_ptr<X3DNode> createLineProperties();
std::shared_ptr<X3DNode> createLineSet();
std::shared_ptr<X3DNode> createListenerPointSource();
std::shared_ptr<X3DNode> createLoadSensor();
std::shared_ptr<X3DNode> createLocalFog();
std::shared_ptr<X3DNode> createMaterial();
std::shared_ptr<X3DNode> createMatrix3VertexAttribute();
std::shared_ptr<X3DNode> createMatrix4VertexAttribute();
std::shared_ptr<X3DNode> createMetadataBoolean();
std::shared_ptr<X3DNode> createMetadataDouble();
std::shared_ptr<X3DNode> createMetadataFloat();
std::shared_ptr<X3DNode> createMetadataInteger();
std::shared_ptr<X3DNode> createMetadataSet();
std::shared_ptr<X3DNode> createMetadataString();
std::shared_ptr<X3DNode> createMicrophoneSource();
std::shared_ptr<X3DNode> createMotorJoint();
std::shared_ptr<X3DNode> createMovieTexture();
std::shared_ptr<X3DNode> createMultiTexture();
std::shared_ptr<X3DNode> createMultiTextureCoordinate();
std::shared_ptr<X3DNode> createMultiTextureTransform();
std::shared_ptr<X3DNode> createNavigationInfo();
std::shared_ptr<X3DNode> createNormal();
std::shared_ptr<X3DNode> createNormalInterpolator();
std::shared_ptr<X3DNode> createNurbsCurve();
std::shared_ptr<X3DNode> createNurbsCurve2D();
std::shared_ptr<X3DNode> createNurbsOrientationInterpolator();
std::shared_ptr<X3DNode> createNurbsPatchSurface();
std::shared_ptr<X3DNode> createNurbsPositionInterpolator();
std::shared_ptr<X3DNode> createNurbsSet();
std::shared_ptr<X3DNode> createNurbsSurfaceInterpolator();
std::shared_ptr<X3DNode> createNurbsSweptSurface();
std::shared_ptr<X3DNode> createNurbsSwungSurface();
std::shared_ptr<X3DNode> createNurbsTextureCoordinate();
std::shared_ptr<X3DNode> createNurbsTrimmedSurface();
std::shared_ptr<X3DNode> createOpacityMapVolumeStyle();
std::shared_ptr<X3DNode> createOrientationChaser();
std::shared_ptr<X3DNode> createOrientationDamper();
std::shared_ptr<X3DNode> createOrientationInterpolator();
std::shared_ptr<X3DNode> createOrthoViewpoint();
std::shared_ptr<X3DNode> createOscillatorSource();
std::shared_ptr<X3DNode> createPackagedShader();
std::shared_ptr<X3DNode> createParticleSystem();
std::shared_ptr<X3DNode> createPeriodicWave();
std::shared_ptr<X3DNode> createPhysicalMaterial();
std::shared_ptr<X3DNode> createPickableGroup();
std::shared_ptr<X3DNode> createPixelTexture();
std::shared_ptr<X3DNode> createPixelTexture3D();
std::shared_ptr<X3DNode> createPlaneSensor();
std::shared_ptr<X3DNode> createPointEmitter();
std::shared_ptr<X3DNode> createPointLight();
std::shared_ptr<X3DNode> createPointPickSensor();
std::shared_ptr<X3DNode> createPointProperties();
std::shared_ptr<X3DNode> createPointSet();
std::shared_ptr<X3DNode> createPolyline2D();
std::shared_ptr<X3DNode> createPolylineEmitter();
std::shared_ptr<X3DNode> createPolypoint2D();
std::shared_ptr<X3DNode> createPositionChaser();
std::shared_ptr<X3DNode> createPositionChaser2D();
std::shared_ptr<X3DNode> createPositionDamper();
std::shared_ptr<X3DNode> createPositionDamper2D();
std::shared_ptr<X3DNode> createPositionInterpolator();
std::shared_ptr<X3DNode> createPositionInterpolator2D();
std::shared_ptr<X3DNode> createPrimitivePickSensor();
std::shared_ptr<X3DNode> createProgramShader();
std::shared_ptr<X3DNode> createProjectionVolumeStyle();
std::shared_ptr<X3DNode> createProtoInstance();
std::shared_ptr<X3DNode> createProximitySensor();
std::shared_ptr<X3DNode> createQuadSet();
std::shared_ptr<X3DNode> createReceiverPdu();
std::shared_ptr<X3DNode> createRectangle2D();
std::shared_ptr<X3DNode> createRigidBody();
std::shared_ptr<X3DNode> createRigidBodyCollection();
std::shared_ptr<X3DNode> createScalarChaser();
std::shared_ptr<X3DNode> createScalarDamper();
std::shared_ptr<X3DNode> createScalarInterpolator();
std::shared_ptr<X3DNode> createScreenFontStyle();
std::shared_ptr<X3DNode> createScreenGroup();
std::shared_ptr<X3DNode> createScript();
std::shared_ptr<X3DNode> createSegmentedVolumeData();
std::shared_ptr<X3DNode> createShadedVolumeStyle();
std::shared_ptr<X3DNode> createShaderPart();
std::shared_ptr<X3DNode> createShaderProgram();
std::shared_ptr<X3DNode> createShape();
std::shared_ptr<X3DNode> createSignalPdu();
std::shared_ptr<X3DNode> createSilhouetteEnhancementVolumeStyle();
std::shared_ptr<X3DNode> createSingleAxisHingeJoint();
std::shared_ptr<X3DNode> createSliderJoint();
std::shared_ptr<X3DNode> createSound();
std::shared_ptr<X3DNode> createSpatialSound();
std::shared_ptr<X3DNode> createSphere();
std::shared_ptr<X3DNode> createSphereSensor();
std::shared_ptr<X3DNode> createSplinePositionInterpolator();
std::shared_ptr<X3DNode> createSplinePositionInterpolator2D();
std::shared_ptr<X3DNode> createSplineScalarInterpolator();
std::shared_ptr<X3DNode> createSpotLight();
std::shared_ptr<X3DNode> createSquadOrientationInterpolator();
std::shared_ptr<X3DNode> createStaticGroup();
std::shared_ptr<X3DNode> createStreamAudioDestination();
std::shared_ptr<X3DNode> createStreamAudioSource();
std::shared_ptr<X3DNode> createStringSensor();
std::shared_ptr<X3DNode> createSurfaceEmitter();
std::shared_ptr<X3DNode> createSwitch();
std::shared_ptr<X3DNode> createTexCoordChaser2D();
std::shared_ptr<X3DNode> createTexCoordDamper2D();
std::shared_ptr<X3DNode> createText();
std::shared_ptr<X3DNode> createTextureBackground();
std::shared_ptr<X3DNode> createTextureCoordinate();
std::shared_ptr<X3DNode> createTextureCoordinate3D();
std::shared_ptr<X3DNode> createTextureCoordinate4D();
std::shared_ptr<X3DNode> createTextureCoordinateGenerator();
std::shared_ptr<X3DNode> createTextureProjector();
std::shared_ptr<X3DNode> createTextureProjectorParallel();
std::shared_ptr<X3DNode> createTextureProperties();
std::shared_ptr<X3DNode> createTextureTransform();
std::shared_ptr<X3DNode> createTextureTransform3D();
std::shared_ptr<X3DNode> createTextureTransformMatrix3D();
std::shared_ptr<X3DNode> createTimeSensor();
std::shared_ptr<X3DNode> createTimeTrigger();
std::shared_ptr<X3DNode> createToneMappedVolumeStyle();
std::shared_ptr<X3DNode> createTouchSensor();
std::shared_ptr<X3DNode> createTransform();
std::shared_ptr<X3DNode> createTransformSensor();
std::shared_ptr<X3DNode> createTransmitterPdu();
std::shared_ptr<X3DNode> createTriangleFanSet();
std::shared_ptr<X3DNode> createTriangleSet();
std::shared_ptr<X3DNode> createTriangleSet2D();
std::shared_ptr<X3DNode> createTriangleStripSet();
std::shared_ptr<X3DNode> createTwoSidedMaterial();
std::shared_ptr<X3DNode> createUniversalJoint();
std::shared_ptr<X3DNode> createUnlitMaterial();
std::shared_ptr<X3DNode> createViewpoint();
std::shared_ptr<X3DNode> createViewpointGroup();
std::shared_ptr<X3DNode> createViewport();
std::shared_ptr<X3DNode> createVisibilitySensor();
std::shared_ptr<X3DNode> createVolumeData();
std::shared_ptr<X3DNode> createVolumeEmitter();
std::shared_ptr<X3DNode> createVolumePickSensor();
std::shared_ptr<X3DNode> createWaveShaper();
std::shared_ptr<X3DNode> createWindPhysicsModel();
std::shared_ptr<X3DNode> createWorldInfo();
} // namespace factory_detail

const std::unordered_map<std::string, X3DNodeFactory::Creator>&
X3DNodeFactory::registry() {
    static const std::unordered_map<std::string, Creator> reg = {
        {"AcousticProperties", &factory_detail::createAcousticProperties},
        {"Analyser", &factory_detail::createAnalyser},
        {"Anchor", &factory_detail::createAnchor},
        {"Appearance", &factory_detail::createAppearance},
        {"Arc2D", &factory_detail::createArc2D},
        {"ArcClose2D", &factory_detail::createArcClose2D},
        {"AudioClip", &factory_detail::createAudioClip},
        {"AudioDestination", &factory_detail::createAudioDestination},
        {"Background", &factory_detail::createBackground},
        {"BallJoint", &factory_detail::createBallJoint},
        {"Billboard", &factory_detail::createBillboard},
        {"BiquadFilter", &factory_detail::createBiquadFilter},
        {"BlendedVolumeStyle", &factory_detail::createBlendedVolumeStyle},
        {"BooleanFilter", &factory_detail::createBooleanFilter},
        {"BooleanSequencer", &factory_detail::createBooleanSequencer},
        {"BooleanToggle", &factory_detail::createBooleanToggle},
        {"BooleanTrigger", &factory_detail::createBooleanTrigger},
        {"BoundaryEnhancementVolumeStyle", &factory_detail::createBoundaryEnhancementVolumeStyle},
        {"BoundedPhysicsModel", &factory_detail::createBoundedPhysicsModel},
        {"Box", &factory_detail::createBox},
        {"BufferAudioSource", &factory_detail::createBufferAudioSource},
        {"CADAssembly", &factory_detail::createCADAssembly},
        {"CADFace", &factory_detail::createCADFace},
        {"CADLayer", &factory_detail::createCADLayer},
        {"CADPart", &factory_detail::createCADPart},
        {"CartoonVolumeStyle", &factory_detail::createCartoonVolumeStyle},
        {"ChannelMerger", &factory_detail::createChannelMerger},
        {"ChannelSelector", &factory_detail::createChannelSelector},
        {"ChannelSplitter", &factory_detail::createChannelSplitter},
        {"Circle2D", &factory_detail::createCircle2D},
        {"ClipPlane", &factory_detail::createClipPlane},
        {"CollidableOffset", &factory_detail::createCollidableOffset},
        {"CollidableShape", &factory_detail::createCollidableShape},
        {"Collision", &factory_detail::createCollision},
        {"CollisionCollection", &factory_detail::createCollisionCollection},
        {"CollisionSensor", &factory_detail::createCollisionSensor},
        {"CollisionSpace", &factory_detail::createCollisionSpace},
        {"Color", &factory_detail::createColor},
        {"ColorChaser", &factory_detail::createColorChaser},
        {"ColorDamper", &factory_detail::createColorDamper},
        {"ColorInterpolator", &factory_detail::createColorInterpolator},
        {"ColorRGBA", &factory_detail::createColorRGBA},
        {"ComposedCubeMapTexture", &factory_detail::createComposedCubeMapTexture},
        {"ComposedShader", &factory_detail::createComposedShader},
        {"ComposedTexture3D", &factory_detail::createComposedTexture3D},
        {"ComposedVolumeStyle", &factory_detail::createComposedVolumeStyle},
        {"Cone", &factory_detail::createCone},
        {"ConeEmitter", &factory_detail::createConeEmitter},
        {"Contact", &factory_detail::createContact},
        {"Contour2D", &factory_detail::createContour2D},
        {"ContourPolyline2D", &factory_detail::createContourPolyline2D},
        {"Convolver", &factory_detail::createConvolver},
        {"Coordinate", &factory_detail::createCoordinate},
        {"CoordinateChaser", &factory_detail::createCoordinateChaser},
        {"CoordinateDamper", &factory_detail::createCoordinateDamper},
        {"CoordinateDouble", &factory_detail::createCoordinateDouble},
        {"CoordinateInterpolator", &factory_detail::createCoordinateInterpolator},
        {"CoordinateInterpolator2D", &factory_detail::createCoordinateInterpolator2D},
        {"Cylinder", &factory_detail::createCylinder},
        {"CylinderSensor", &factory_detail::createCylinderSensor},
        {"DISEntityManager", &factory_detail::createDISEntityManager},
        {"DISEntityTypeMapping", &factory_detail::createDISEntityTypeMapping},
        {"Delay", &factory_detail::createDelay},
        {"DirectionalLight", &factory_detail::createDirectionalLight},
        {"Disk2D", &factory_detail::createDisk2D},
        {"DoubleAxisHingeJoint", &factory_detail::createDoubleAxisHingeJoint},
        {"DynamicsCompressor", &factory_detail::createDynamicsCompressor},
        {"EaseInEaseOut", &factory_detail::createEaseInEaseOut},
        {"EdgeEnhancementVolumeStyle", &factory_detail::createEdgeEnhancementVolumeStyle},
        {"ElevationGrid", &factory_detail::createElevationGrid},
        {"EspduTransform", &factory_detail::createEspduTransform},
        {"ExplosionEmitter", &factory_detail::createExplosionEmitter},
        {"Extrusion", &factory_detail::createExtrusion},
        {"FillProperties", &factory_detail::createFillProperties},
        {"FloatVertexAttribute", &factory_detail::createFloatVertexAttribute},
        {"Fog", &factory_detail::createFog},
        {"FogCoordinate", &factory_detail::createFogCoordinate},
        {"FontStyle", &factory_detail::createFontStyle},
        {"ForcePhysicsModel", &factory_detail::createForcePhysicsModel},
        {"Gain", &factory_detail::createGain},
        {"GeneratedCubeMapTexture", &factory_detail::createGeneratedCubeMapTexture},
        {"GeoCoordinate", &factory_detail::createGeoCoordinate},
        {"GeoElevationGrid", &factory_detail::createGeoElevationGrid},
        {"GeoLOD", &factory_detail::createGeoLOD},
        {"GeoLocation", &factory_detail::createGeoLocation},
        {"GeoMetadata", &factory_detail::createGeoMetadata},
        {"GeoOrigin", &factory_detail::createGeoOrigin},
        {"GeoPositionInterpolator", &factory_detail::createGeoPositionInterpolator},
        {"GeoProximitySensor", &factory_detail::createGeoProximitySensor},
        {"GeoTouchSensor", &factory_detail::createGeoTouchSensor},
        {"GeoTransform", &factory_detail::createGeoTransform},
        {"GeoViewpoint", &factory_detail::createGeoViewpoint},
        {"Group", &factory_detail::createGroup},
        {"HAnimDisplacer", &factory_detail::createHAnimDisplacer},
        {"HAnimHumanoid", &factory_detail::createHAnimHumanoid},
        {"HAnimJoint", &factory_detail::createHAnimJoint},
        {"HAnimMotion", &factory_detail::createHAnimMotion},
        {"HAnimSegment", &factory_detail::createHAnimSegment},
        {"HAnimSite", &factory_detail::createHAnimSite},
        {"ImageCubeMapTexture", &factory_detail::createImageCubeMapTexture},
        {"ImageTexture", &factory_detail::createImageTexture},
        {"ImageTexture3D", &factory_detail::createImageTexture3D},
        {"IndexedFaceSet", &factory_detail::createIndexedFaceSet},
        {"IndexedLineSet", &factory_detail::createIndexedLineSet},
        {"IndexedQuadSet", &factory_detail::createIndexedQuadSet},
        {"IndexedTriangleFanSet", &factory_detail::createIndexedTriangleFanSet},
        {"IndexedTriangleSet", &factory_detail::createIndexedTriangleSet},
        {"IndexedTriangleStripSet", &factory_detail::createIndexedTriangleStripSet},
        {"Inline", &factory_detail::createInline},
        {"IntegerSequencer", &factory_detail::createIntegerSequencer},
        {"IntegerTrigger", &factory_detail::createIntegerTrigger},
        {"IsoSurfaceVolumeData", &factory_detail::createIsoSurfaceVolumeData},
        {"KeySensor", &factory_detail::createKeySensor},
        {"LOD", &factory_detail::createLOD},
        {"Layer", &factory_detail::createLayer},
        {"LayerSet", &factory_detail::createLayerSet},
        {"Layout", &factory_detail::createLayout},
        {"LayoutGroup", &factory_detail::createLayoutGroup},
        {"LayoutLayer", &factory_detail::createLayoutLayer},
        {"LinePickSensor", &factory_detail::createLinePickSensor},
        {"LineProperties", &factory_detail::createLineProperties},
        {"LineSet", &factory_detail::createLineSet},
        {"ListenerPointSource", &factory_detail::createListenerPointSource},
        {"LoadSensor", &factory_detail::createLoadSensor},
        {"LocalFog", &factory_detail::createLocalFog},
        {"Material", &factory_detail::createMaterial},
        {"Matrix3VertexAttribute", &factory_detail::createMatrix3VertexAttribute},
        {"Matrix4VertexAttribute", &factory_detail::createMatrix4VertexAttribute},
        {"MetadataBoolean", &factory_detail::createMetadataBoolean},
        {"MetadataDouble", &factory_detail::createMetadataDouble},
        {"MetadataFloat", &factory_detail::createMetadataFloat},
        {"MetadataInteger", &factory_detail::createMetadataInteger},
        {"MetadataSet", &factory_detail::createMetadataSet},
        {"MetadataString", &factory_detail::createMetadataString},
        {"MicrophoneSource", &factory_detail::createMicrophoneSource},
        {"MotorJoint", &factory_detail::createMotorJoint},
        {"MovieTexture", &factory_detail::createMovieTexture},
        {"MultiTexture", &factory_detail::createMultiTexture},
        {"MultiTextureCoordinate", &factory_detail::createMultiTextureCoordinate},
        {"MultiTextureTransform", &factory_detail::createMultiTextureTransform},
        {"NavigationInfo", &factory_detail::createNavigationInfo},
        {"Normal", &factory_detail::createNormal},
        {"NormalInterpolator", &factory_detail::createNormalInterpolator},
        {"NurbsCurve", &factory_detail::createNurbsCurve},
        {"NurbsCurve2D", &factory_detail::createNurbsCurve2D},
        {"NurbsOrientationInterpolator", &factory_detail::createNurbsOrientationInterpolator},
        {"NurbsPatchSurface", &factory_detail::createNurbsPatchSurface},
        {"NurbsPositionInterpolator", &factory_detail::createNurbsPositionInterpolator},
        {"NurbsSet", &factory_detail::createNurbsSet},
        {"NurbsSurfaceInterpolator", &factory_detail::createNurbsSurfaceInterpolator},
        {"NurbsSweptSurface", &factory_detail::createNurbsSweptSurface},
        {"NurbsSwungSurface", &factory_detail::createNurbsSwungSurface},
        {"NurbsTextureCoordinate", &factory_detail::createNurbsTextureCoordinate},
        {"NurbsTrimmedSurface", &factory_detail::createNurbsTrimmedSurface},
        {"OpacityMapVolumeStyle", &factory_detail::createOpacityMapVolumeStyle},
        {"OrientationChaser", &factory_detail::createOrientationChaser},
        {"OrientationDamper", &factory_detail::createOrientationDamper},
        {"OrientationInterpolator", &factory_detail::createOrientationInterpolator},
        {"OrthoViewpoint", &factory_detail::createOrthoViewpoint},
        {"OscillatorSource", &factory_detail::createOscillatorSource},
        {"PackagedShader", &factory_detail::createPackagedShader},
        {"ParticleSystem", &factory_detail::createParticleSystem},
        {"PeriodicWave", &factory_detail::createPeriodicWave},
        {"PhysicalMaterial", &factory_detail::createPhysicalMaterial},
        {"PickableGroup", &factory_detail::createPickableGroup},
        {"PixelTexture", &factory_detail::createPixelTexture},
        {"PixelTexture3D", &factory_detail::createPixelTexture3D},
        {"PlaneSensor", &factory_detail::createPlaneSensor},
        {"PointEmitter", &factory_detail::createPointEmitter},
        {"PointLight", &factory_detail::createPointLight},
        {"PointPickSensor", &factory_detail::createPointPickSensor},
        {"PointProperties", &factory_detail::createPointProperties},
        {"PointSet", &factory_detail::createPointSet},
        {"Polyline2D", &factory_detail::createPolyline2D},
        {"PolylineEmitter", &factory_detail::createPolylineEmitter},
        {"Polypoint2D", &factory_detail::createPolypoint2D},
        {"PositionChaser", &factory_detail::createPositionChaser},
        {"PositionChaser2D", &factory_detail::createPositionChaser2D},
        {"PositionDamper", &factory_detail::createPositionDamper},
        {"PositionDamper2D", &factory_detail::createPositionDamper2D},
        {"PositionInterpolator", &factory_detail::createPositionInterpolator},
        {"PositionInterpolator2D", &factory_detail::createPositionInterpolator2D},
        {"PrimitivePickSensor", &factory_detail::createPrimitivePickSensor},
        {"ProgramShader", &factory_detail::createProgramShader},
        {"ProjectionVolumeStyle", &factory_detail::createProjectionVolumeStyle},
        {"ProtoInstance", &factory_detail::createProtoInstance},
        {"ProximitySensor", &factory_detail::createProximitySensor},
        {"QuadSet", &factory_detail::createQuadSet},
        {"ReceiverPdu", &factory_detail::createReceiverPdu},
        {"Rectangle2D", &factory_detail::createRectangle2D},
        {"RigidBody", &factory_detail::createRigidBody},
        {"RigidBodyCollection", &factory_detail::createRigidBodyCollection},
        {"ScalarChaser", &factory_detail::createScalarChaser},
        {"ScalarDamper", &factory_detail::createScalarDamper},
        {"ScalarInterpolator", &factory_detail::createScalarInterpolator},
        {"ScreenFontStyle", &factory_detail::createScreenFontStyle},
        {"ScreenGroup", &factory_detail::createScreenGroup},
        {"Script", &factory_detail::createScript},
        {"SegmentedVolumeData", &factory_detail::createSegmentedVolumeData},
        {"ShadedVolumeStyle", &factory_detail::createShadedVolumeStyle},
        {"ShaderPart", &factory_detail::createShaderPart},
        {"ShaderProgram", &factory_detail::createShaderProgram},
        {"Shape", &factory_detail::createShape},
        {"SignalPdu", &factory_detail::createSignalPdu},
        {"SilhouetteEnhancementVolumeStyle", &factory_detail::createSilhouetteEnhancementVolumeStyle},
        {"SingleAxisHingeJoint", &factory_detail::createSingleAxisHingeJoint},
        {"SliderJoint", &factory_detail::createSliderJoint},
        {"Sound", &factory_detail::createSound},
        {"SpatialSound", &factory_detail::createSpatialSound},
        {"Sphere", &factory_detail::createSphere},
        {"SphereSensor", &factory_detail::createSphereSensor},
        {"SplinePositionInterpolator", &factory_detail::createSplinePositionInterpolator},
        {"SplinePositionInterpolator2D", &factory_detail::createSplinePositionInterpolator2D},
        {"SplineScalarInterpolator", &factory_detail::createSplineScalarInterpolator},
        {"SpotLight", &factory_detail::createSpotLight},
        {"SquadOrientationInterpolator", &factory_detail::createSquadOrientationInterpolator},
        {"StaticGroup", &factory_detail::createStaticGroup},
        {"StreamAudioDestination", &factory_detail::createStreamAudioDestination},
        {"StreamAudioSource", &factory_detail::createStreamAudioSource},
        {"StringSensor", &factory_detail::createStringSensor},
        {"SurfaceEmitter", &factory_detail::createSurfaceEmitter},
        {"Switch", &factory_detail::createSwitch},
        {"TexCoordChaser2D", &factory_detail::createTexCoordChaser2D},
        {"TexCoordDamper2D", &factory_detail::createTexCoordDamper2D},
        {"Text", &factory_detail::createText},
        {"TextureBackground", &factory_detail::createTextureBackground},
        {"TextureCoordinate", &factory_detail::createTextureCoordinate},
        {"TextureCoordinate3D", &factory_detail::createTextureCoordinate3D},
        {"TextureCoordinate4D", &factory_detail::createTextureCoordinate4D},
        {"TextureCoordinateGenerator", &factory_detail::createTextureCoordinateGenerator},
        {"TextureProjector", &factory_detail::createTextureProjector},
        {"TextureProjectorParallel", &factory_detail::createTextureProjectorParallel},
        {"TextureProperties", &factory_detail::createTextureProperties},
        {"TextureTransform", &factory_detail::createTextureTransform},
        {"TextureTransform3D", &factory_detail::createTextureTransform3D},
        {"TextureTransformMatrix3D", &factory_detail::createTextureTransformMatrix3D},
        {"TimeSensor", &factory_detail::createTimeSensor},
        {"TimeTrigger", &factory_detail::createTimeTrigger},
        {"ToneMappedVolumeStyle", &factory_detail::createToneMappedVolumeStyle},
        {"TouchSensor", &factory_detail::createTouchSensor},
        {"Transform", &factory_detail::createTransform},
        {"TransformSensor", &factory_detail::createTransformSensor},
        {"TransmitterPdu", &factory_detail::createTransmitterPdu},
        {"TriangleFanSet", &factory_detail::createTriangleFanSet},
        {"TriangleSet", &factory_detail::createTriangleSet},
        {"TriangleSet2D", &factory_detail::createTriangleSet2D},
        {"TriangleStripSet", &factory_detail::createTriangleStripSet},
        {"TwoSidedMaterial", &factory_detail::createTwoSidedMaterial},
        {"UniversalJoint", &factory_detail::createUniversalJoint},
        {"UnlitMaterial", &factory_detail::createUnlitMaterial},
        {"Viewpoint", &factory_detail::createViewpoint},
        {"ViewpointGroup", &factory_detail::createViewpointGroup},
        {"Viewport", &factory_detail::createViewport},
        {"VisibilitySensor", &factory_detail::createVisibilitySensor},
        {"VolumeData", &factory_detail::createVolumeData},
        {"VolumeEmitter", &factory_detail::createVolumeEmitter},
        {"VolumePickSensor", &factory_detail::createVolumePickSensor},
        {"WaveShaper", &factory_detail::createWaveShaper},
        {"WindPhysicsModel", &factory_detail::createWindPhysicsModel},
        {"WorldInfo", &factory_detail::createWorldInfo},
    };
    return reg;
}

std::shared_ptr<X3DNode> X3DNodeFactory::create(const std::string& typeName) {
    const auto& reg = registry();
    auto it = reg.find(typeName);
    return it == reg.end() ? nullptr : it->second();
}

std::shared_ptr<X3DNode> createX3DNode(const std::string& typeName) {
    return X3DNodeFactory::create(typeName);
}

} // namespace x3d::nodes
