# Exercise input failures in Release/NDEBUG too. These are ordinary runtime
# errors before scene creation, not assertions or a separate test-only parser.
file(MAKE_DIRECTORY "${TEST_DIRECTORY}")
function(expect_rejection name contents diagnostic)
  set(path "${TEST_DIRECTORY}/${name}.txt")
  file(WRITE "${path}" "${contents}")
  execute_process(COMMAND "${HOST_EXECUTABLE}" "${path}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 3)
  if(NOT status EQUAL 1 OR NOT error MATCHES "${diagnostic}")
    message(FATAL_ERROR "${name}: expected checked rejection, got ${status}: ${output}${error}")
  endif()
endfunction()
expect_rejection(unknown "0 dance\n" "unknown operation")
expect_rejection(bad_number "nan fraction 0\n" "finite.*time")
expect_rejection(regressing "1 fraction 0\n0 fraction 1\n" "nondecreasing")
expect_rejection(fraction_range "0 fraction 1.5\n" "fraction must be")
expect_rejection(trailing "0 fraction 0 garbage\n" "trailing token")
expect_rejection(missing_argument "0 swap\n" "swap requires")
expect_rejection(incomplete "0 fraction 0\n" "multiple of three")
string(REPEAT "x" 257 long_line)
expect_rejection(long_line "${long_line}\n" "256 bytes")
string(REPEAT "#" 65537 huge_file)
expect_rejection(oversized "${huge_file}" "64 KiB")
string(REPEAT "0 idle\n" 121 too_many)
expect_rejection(too_many "${too_many}" "120 host turns")
message(STATUS "Ten malformed/oversized workloads rejected with checked errors")
