// tools/x3d-cli/canon_gate.cpp
// ─────────────────────────────────────────────────────────────────────────────
// X3DC14N Tiered Gate — three-tier differential test for x3d canonicalize:
//
//   TIER 1  Idempotence (Java-FREE, HARD CI gate):
//     canonicalize(canonicalize(x)) == canonicalize(x) byte-for-byte over
//     the XML subset. A canonical form MUST be a fixed point. 100% required.
//     ANY idempotence failure is always a regression — no exceptions.
//
//   TIER 2  Tolerant diff vs X3DJSAIL (structural agreement, baseline-locked):
//     Compare OUR canonical output to committed X3DJSAIL golden fixtures
//     (tools/x3d-cli/goldens/canonical-goldens/) with a TOLERANT text diff:
//     numbers compared within relative tolerance, insignificant whitespace
//     normalized. Agreement = our structural + numeric form matches the oracle.
//
//   TIER 3  Byte-exact (stretch metric, informative):
//     Fraction of subset files where OUR canonical output == X3DJSAIL's byte-
//     for-byte. Reports the gap; NOT a gate.
//
// Exit modes:
//   Default (informative): Tier-1 failures → exit 1; rest → exit 0.
//   --write-baseline: writes canon-gate-baseline.tsv with per-item T1+T2 state.
//   --gate: Tier-1 ANY failure → exit 1 (hard gate, 100% required).
//           Tier-2 per-item: PASS->FAIL is a regression → exit 1.
//           FAIL->PASS (improvement) → note to refresh baseline.
//
// Usage:
//   canon_gate <x3d_binary> <corpus_root> <goldens_dir> [--gate | --write-baseline]
//
//   x3d_binary   — path to the built x3d CLI binary
//   corpus_root  — a local X3D conformance archive checkout ($X3D_CORPUS_DIR)
//   goldens_dir  — tools/x3d-cli/goldens
//
// The golden fixtures for tier 2/3 live in:
//   <goldens_dir>/canonical-goldens/<relpath>Canonical.xml
// They are generated by gen_canon_goldens.sh (run once, committed).
// If no goldens directory exists, tier 2/3 are skipped (tier 1 always runs).
// ─────────────────────────────────────────────────────────────────────────────
#include "x3d/sdk.hpp"

#include <algorithm>
#include <cassert>
#include <cctype>
#include <charconv>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <thread>
#include <vector>

namespace fs = std::filesystem;
namespace sdk = x3d::sdk;

// ── helpers ───────────────────────────────────────────────────────────────────

static std::string readFile(const std::string &path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) throw std::runtime_error("cannot open: " + path);
    std::ostringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

static std::string toLower(std::string s) {
    for (char &c : s) c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    return s;
}

static std::string extOf(const std::string &p) {
    return toLower(fs::path(p).extension().string());
}

static std::vector<std::string> loadSubset(const std::string &path) {
    std::vector<std::string> out;
    std::ifstream f(path);
    if (!f) throw std::runtime_error("cannot open subset: " + path);
    std::string line;
    while (std::getline(f, line)) {
        if (!line.empty()) out.push_back(line);
    }
    return out;
}

// ── Canonicalize via CLI subprocess ──────────────────────────────────────────
// Using subprocess for process isolation: the DynamicFieldStore (global
// singleton keyed on node pointer) accumulates entries across same-process
// parse calls. On pass 2, new nodes may reuse freed addresses from pass 1
// and pick up phantom author fields. Subprocess invocation avoids this.

static std::string g_x3dBin; // set from argv[1] in main()

// Invoke `x3d canonicalize <path>` as a subprocess; return stdout.
// Throws on non-zero exit or pipe failure.
static std::string canonicalizeViaProc(const std::string &path) {
    // Single-quote the path for the shell, escaping any embedded single-quotes.
    std::string qpath = "'";
    for (char c : path) {
        if (c == '\'') qpath += "'\\''";
        else qpath += c;
    }
    qpath += "'";
    const std::string cmd = g_x3dBin + " canonicalize " + qpath + " 2>/dev/null";
    FILE *pipe = popen(cmd.c_str(), "r");
    if (!pipe) throw std::runtime_error("popen failed: " + cmd);
    std::string result;
    char buf[4096];
    while (fgets(buf, sizeof(buf), pipe)) result += buf;
    int rc = pclose(pipe);
    if (rc != 0) throw std::runtime_error("x3d canonicalize failed (rc=" + std::to_string(rc) + "): " + path);
    return result;
}

// Write content to a temp file; return path. Caller must remove it.
static std::string writeTempFile(const std::string &content, const std::string &suffix = ".x3d") {
    std::string tmpl = "/tmp/canon_gate_XXXXXX" + suffix;
    // Use mkstemp-style via C++ filesystem tmp path.
    auto tp = fs::temp_directory_path() / ("canon_gate_" + std::to_string(std::hash<std::thread::id>{}(std::this_thread::get_id())) + suffix);
    std::ofstream f(tp, std::ios::binary | std::ios::trunc);
    if (!f) throw std::runtime_error("cannot write temp file: " + tp.string());
    f << content;
    return tp.string();
}

// Pass 1: canonicalize an original corpus file.
static std::string canonicalize(const std::string &path) {
    return canonicalizeViaProc(path);
}

// Pass 2: re-canonicalize canonical XML from pass 1 (write to temp, invoke CLI).
static std::string canonicalizeString(const std::string &xml) {
    std::string tmp = writeTempFile(xml, ".x3d");
    try {
        std::string r = canonicalizeViaProc(tmp);
        fs::remove(tmp);
        return r;
    } catch (...) {
        fs::remove(tmp);
        throw;
    }
}

// ── Tolerant diff (tier 2) ────────────────────────────────────────────────────
//
// Strategy: normalize both canonical XML strings into a flat sequence of
// "semantic tokens" — element names, attribute names, attribute values
// (split on whitespace inside), CDATA text lines — then compare sequences
// tolerantly: numbers within relative 1e-5, leading-zero differences accepted.
//
// Known structural differences tolerated explicitly:
//   1. containerField: we always emit it; JSAIL omits for default-slot children.
//      → Strip containerField attrs from OUR token stream before comparing.
//   2. JSAIL number formats vs ours: JSAIL uses %.6f for doubles, %g with .0
//      for floats; we use shortest-rep (no trailing zeros). Tolerated by
//      numeric comparison (parseTok handles ".005" and "0.005" equally).
//   3. JSAIL preserves XML comments; ours strips them → strip comments in JSAIL.
//
// NOT tolerated (these would indicate a real structural mismatch):
//   - Different element names or attribute names.
//   - Different child ordering (both use field-table order).
//   - Different attribute sequence (both sort alphabetically).

// Parse a double from a string (supports ".005" style); returns NaN on failure.
static double parseTok(const std::string &s) {
    // strtod handles ".005", "-.5", "1.0", "45.000000", etc.
    char *end = nullptr;
    double v = std::strtod(s.c_str(), &end);
    if (end == s.c_str() || end != s.c_str() + s.size()) return std::numeric_limits<double>::quiet_NaN();
    return v;
}

static bool numericClose(const std::string &a, const std::string &b, double tol = 1e-5) {
    double va = parseTok(a), vb = parseTok(b);
    if (std::isnan(va) || std::isnan(vb)) return false;
    double denom = std::max({std::fabs(va), std::fabs(vb), 1.0});
    return std::fabs(va - vb) / denom < tol;
}

// Normalize an XML string into a sequence of semantic tokens for tolerant diff:
//   - Strip <!-- ... --> comments.
//   - Skip XML prolog (<?xml ...?>) and DOCTYPE.
//   - For each element: emit "elemName", then each attr as "attrName" "attrVal..."
//     (attr values are split on whitespace for MF multi-value attrs).
//   - For CDATA, emit each non-empty line as a token.
// Structural punctuation (<, >, /, =, quotes) is consumed; only names/values emitted.
static std::vector<std::string> normalizeXml(const std::string &src,
                                              bool stripContainerField) {
    std::vector<std::string> out;
    std::size_t i = 0;
    const std::size_t n = src.size();

    auto skip_ws = [&]() { while (i < n && std::isspace((unsigned char)src[i])) ++i; };
    auto peek = [&](std::size_t off = 0) -> char { return (i + off < n) ? src[i + off] : 0; };

    auto read_word = [&]() {
        std::size_t j = i;
        while (j < n && src[j] != '=' && src[j] != '>' && src[j] != '/'
               && src[j] != '<' && !std::isspace((unsigned char)src[j])) ++j;
        std::string w = src.substr(i, j - i);
        i = j;
        return w;
    };

    // Split a value string on whitespace → individual tokens pushed to out.
    auto push_val_tokens = [&](const std::string &v) {
        std::size_t p = 0;
        while (p < v.size()) {
            while (p < v.size() && std::isspace((unsigned char)v[p])) ++p;
            std::size_t q = p;
            while (q < v.size() && !std::isspace((unsigned char)v[q])) ++q;
            if (q > p) out.push_back(v.substr(p, q - p));
            p = q;
        }
    };

    while (i < n) {
        skip_ws();
        if (i >= n) break;

        if (src[i] != '<') {
            // Text content (e.g. CDATA text after ]]>). Push non-empty tokens.
            std::size_t j = src.find('<', i);
            if (j == std::string::npos) j = n;
            std::string txt = src.substr(i, j - i);
            push_val_tokens(txt);
            i = j;
            continue;
        }

        ++i; // consume '<'

        // Comment: <!-- ... -->
        if (i + 2 < n && src[i] == '!' && src[i+1] == '-' && src[i+2] == '-') {
            std::size_t end = src.find("-->", i);
            i = (end == std::string::npos) ? n : end + 3;
            continue;
        }

        // CDATA section: <![CDATA[ ... ]]>
        if (i + 7 < n && src.substr(i, 7) == "![CDATA") {
            std::size_t start = src.find("[[", i);
            if (start == std::string::npos) { i = n; break; }
            start += 2;
            std::size_t end = src.find("]]>", start);
            if (end == std::string::npos) end = n;
            // For CDATA (Script source), push each non-empty line as-is.
            std::string cdata = src.substr(start, end - start);
            std::istringstream ss(cdata);
            std::string line;
            while (std::getline(ss, line)) {
                // Trim trailing whitespace.
                while (!line.empty() && std::isspace((unsigned char)line.back())) line.pop_back();
                if (!line.empty()) out.push_back("CDATA:" + line);
            }
            i = (end == std::string::npos) ? n : end + 3;
            continue;
        }

        // DOCTYPE: <!DOCTYPE ...>
        if (i < n && src[i] == '!') {
            std::size_t end = src.find('>', i);
            i = (end == std::string::npos) ? n : end + 1;
            continue;
        }

        // Processing instruction: <?...?>
        if (i < n && src[i] == '?') {
            std::size_t end = src.find("?>", i);
            i = (end == std::string::npos) ? n : end + 2;
            continue;
        }

        // Closing tag: </ElemName>
        if (i < n && src[i] == '/') {
            std::size_t end = src.find('>', i);
            i = (end == std::string::npos) ? n : end + 1;
            continue;  // close tags carry no semantic info; element name already emitted
        }

        // Opening tag: <ElemName attr='val' ...> or <ElemName .../>
        skip_ws();
        std::string elem = read_word();
        if (!elem.empty()) out.push_back(elem);

        // Parse attributes.
        while (i < n && src[i] != '>' && !(src[i] == '/' && peek(1) == '>')) {
            skip_ws();
            if (i >= n || src[i] == '>' || (src[i] == '/' && peek(1) == '>')) break;
            // Attribute name.
            std::string attrName = read_word();
            if (attrName.empty()) { ++i; continue; }
            // '='
            skip_ws();
            if (i < n && src[i] == '=') ++i;
            // Quoted value.
            skip_ws();
            char q = (i < n) ? src[i] : 0;
            std::string attrVal;
            if (q == '\'' || q == '"') {
                ++i; // open quote
                std::size_t vend = src.find(q, i);
                if (vend == std::string::npos) vend = n;
                attrVal = src.substr(i, vend - i);
                i = (vend < n) ? vend + 1 : n;
            } else {
                attrVal = read_word();
            }
            // Skip containerField attr if requested.
            if (stripContainerField && attrName == "containerField") continue;
            // Skip xmlns:xsd and xsd:noNamespaceSchemaLocation from ours
            // (we always add them; JSAIL only adds them when already present in source).
            if (stripContainerField &&
                (attrName == "xmlns:xsd" || attrName == "xsd:noNamespaceSchemaLocation")) continue;
            // Push attrName + value tokens.
            out.push_back(attrName);
            push_val_tokens(attrVal);
        }
        // Consume '>' or '/>'
        if (i < n && src[i] == '/') ++i;
        if (i < n && src[i] == '>') ++i;
    }
    return out;
}

// Tolerant comparison of two canonical XML strings.
// Returns (agreed, reason_if_not).
static std::pair<bool, std::string> tolerantDiff(const std::string &jsail,
                                                   const std::string &ours) {
    // Quick byte-exact check first.
    if (jsail == ours) return {true, ""};

    // Normalize both to semantic token streams.
    // Strip containerField from BOTH (JSAIL inconsistently emits/omits it;
    // we always emit it; stripping both normalizes the comparison).
    auto tokJ = normalizeXml(jsail, true);
    auto tokO = normalizeXml(ours,  true);

    // Token-by-token comparison.
    std::size_t jIdx = 0, oIdx = 0;
    while (jIdx < tokJ.size() && oIdx < tokO.size()) {
        const std::string &tj = tokJ[jIdx];
        const std::string &to = tokO[oIdx];
        if (tj == to) { ++jIdx; ++oIdx; continue; }
        // Try numeric tolerance (handles ".005" vs "0.005", "45.000000" vs "45", etc.)
        if (numericClose(tj, to)) { ++jIdx; ++oIdx; continue; }
        // Tolerate MFString inner-quote differences: JSAIL keeps `"value"`, we strip quotes.
        // Normalize by stripping surrounding double-quotes from both tokens.
        auto stripDQ = [](const std::string &s) -> std::string {
            if (s.size() >= 2 && s.front() == '"' && s.back() == '"')
                return s.substr(1, s.size() - 2);
            return s;
        };
        if (stripDQ(tj) == stripDQ(to)) { ++jIdx; ++oIdx; continue; }
        // Mismatch.
        std::ostringstream r;
        r << "token " << jIdx << ": jsail='" << tj << "' ours='" << to << "'";
        return {false, r.str()};
    }
    if (jIdx != tokJ.size() || oIdx != tokO.size()) {
        std::ostringstream r;
        r << "token count mismatch: jsail=" << tokJ.size() << " ours=" << tokO.size();
        return {false, r.str()};
    }
    return {true, ""};
}

// ── Baseline PASS/FAIL state (regression gate) ───────────────────────────────
//
// Key format: "canon-t1\t<relpath>" or "canon-t2\t<relpath>"
// Value: "PASS" or "FAIL"
using BaselineMap = std::unordered_map<std::string, std::string>;

static BaselineMap loadBaseline(const std::string &path) {
    BaselineMap out;
    std::ifstream f(path);
    if (!f) return out;
    std::string line;
    bool header = true;
    while (std::getline(f, line)) {
        if (header) { header = false; continue; }
        if (line.empty() || line[0] == '#') continue;
        auto tab = line.find('\t');
        if (tab == std::string::npos) continue;
        out[line.substr(0, tab)] = line.substr(tab + 1);
    }
    return out;
}

static void writeBaseline(const std::string &path, const BaselineMap &bm,
                          int t1pass, int t1total, int t2pass, int t2total) {
    std::ofstream f(path);
    if (!f) throw std::runtime_error("cannot write baseline: " + path);
    f << "# canon-gate baseline — generated by x3d_canon_gate --write-baseline\n";
    f << "# T1-idempotence: " << t1pass << "/" << t1total
      << "  T2-tolerant: " << t2pass << "/" << t2total << "\n";
    f << "check_key\tresult\n";
    std::vector<std::pair<std::string,std::string>> rows(bm.begin(), bm.end());
    std::sort(rows.begin(), rows.end());
    for (const auto &[k, v] : rows)
        f << k << "\t" << v << "\n";
}

// ── main ─────────────────────────────────────────────────────────────────────

int main(int argc, char **argv) {
    // Parse optional mode flag.
    bool gateMode = false;
    bool writeBaselineMode = false;
    int positionalArgc = argc;
    if (argc >= 2) {
        std::string last = argv[argc - 1];
        if (last == "--gate") { gateMode = true; positionalArgc = argc - 1; }
        else if (last == "--write-baseline") { writeBaselineMode = true; positionalArgc = argc - 1; }
    }

    if (positionalArgc < 4) {
        std::cerr << "usage: canon_gate <x3d_binary> <corpus_root> <goldens_dir>"
                     " [--gate | --write-baseline]\n";
        return 1;
    }
    const std::string x3dBin     = argv[1];
    const std::string corpusRoot = argv[2];
    const std::string goldensDir = argv[3];

    g_x3dBin = argv[1]; // set subprocess path

    const std::string baselinePath = goldensDir + "/canon-gate-baseline.tsv";

    if (gateMode)
        std::cout << "[--gate mode] Regression check against baseline: " << baselinePath << "\n\n";
    else if (writeBaselineMode)
        std::cout << "[--write-baseline mode] Capturing current state to: " << baselinePath << "\n\n";

    // Load baseline if in gate mode.
    BaselineMap baseline;
    if (gateMode) {
        baseline = loadBaseline(baselinePath);
        if (baseline.empty()) {
            std::cerr << "ERROR: baseline not found or empty: " << baselinePath << "\n";
            std::cerr << "Run 'mise run cli-gate-baseline' first.\n";
            return 1;
        }
        std::cout << "Loaded " << baseline.size() << " baseline entries.\n\n";
    }

    const std::string subsetTxt     = goldensDir + "/subset.txt";
    const std::string canonGoldDir  = goldensDir + "/canonical-goldens";

    // Load the XML-only subset.
    std::cout << "Loading subset from " << subsetTxt << "...\n";
    std::vector<std::string> subset;
    try {
        auto all = loadSubset(subsetTxt);
        for (const auto &rel : all) {
            if (extOf(rel) == ".x3d") subset.push_back(rel);
        }
    } catch (const std::exception &e) {
        std::cerr << "ERROR: " << e.what() << "\nRun 'mise run cli-golden-gen' first.\n";
        return 1;
    }
    std::cout << "Subset (XML files only): " << subset.size() << "\n\n";

    // Per-item PASS/FAIL tracking for baseline write / regression gate.
    BaselineMap currentState;

    // ── TIER 1: Idempotence ───────────────────────────────────────────────────
    std::cout << "=== TIER 1: Idempotence (canonicalize(canonicalize(x)) == canonicalize(x)) ===\n";

    int t1total = 0, t1pass = 0, t1fail = 0, t1skip = 0;
    std::vector<std::string> t1failures;

    for (const auto &rel : subset) {
        const std::string abs = corpusRoot + "/" + rel;
        if (!fs::exists(abs)) { ++t1skip; continue; }

        try {
            // First canonicalization.
            std::string c1 = canonicalize(abs);
            // Second canonicalization (re-parse + re-write).
            std::string c2 = canonicalizeString(c1);

            ++t1total;
            if (c1 == c2) {
                ++t1pass;
                currentState["canon-t1:" + rel] = "PASS";
            } else {
                ++t1fail;
                t1failures.push_back(rel);
                currentState["canon-t1:" + rel] = "FAIL";
            }
        } catch (const std::exception &e) {
            ++t1skip; // parse/IO error — not recorded in state (can't distinguish from missing file)
        }
    }

    double t1rate = t1total > 0 ? 100.0 * t1pass / t1total : 0.0;
    std::cout << "  Total: " << t1total << " | Pass: " << t1pass
              << " | Fail: " << t1fail << " | Skip: " << t1skip << "\n";
    std::cout << "  TIER 1 idempotence rate: " << t1pass << "/" << t1total
              << " (" << static_cast<int>(t1rate + 0.5) << "%)\n";
    if (!t1failures.empty()) {
        std::cout << "  Idempotence failures (up to 5):\n";
        for (std::size_t i = 0; i < std::min(t1failures.size(), std::size_t(5)); ++i)
            std::cout << "    - " << t1failures[i] << "\n";
    }
    std::cout << "\n";

    // ── TIER 2 + 3: Differential vs X3DJSAIL goldens ─────────────────────────
    bool goldensExist = fs::is_directory(canonGoldDir);
    int t2total = 0, t2pass = 0, t3exact = 0;
    if (!goldensExist) {
        // The canonical goldens are deliberately NOT committed (derivatives of
        // the Web3D example archive: per-file attribution + ~7.4MB — same
        // policy that keeps the corpus itself out of git), so a fresh clone
        // cannot run tier-2/3. That is a COVERAGE GAP, not a pass: say so
        // unmissably in both modes instead of the old two-line skip note that
        // let "PASS" read as full coverage.
        std::cout << "=== TIER 2/3: *** NOT RUN — 0 of the tier-2/3 checks executed ***\n";
        std::cout << "    No canonical goldens at " << canonGoldDir << ".\n";
        std::cout << "    They are local-only fixtures (Web3D-derived; not bundled).\n";
        std::cout << "    Enable locally: mise run canon-golden-gen  (JDK >= 25 + X3DJSAIL.jar)\n\n";
    } else {
        std::cout << "=== TIER 2: Tolerant diff vs X3DJSAIL goldens ===\n";
        std::cout << "=== TIER 3: Byte-exact match vs X3DJSAIL ===\n\n";

        std::vector<std::pair<std::string,std::string>> t2failures; // (rel, reason)

        for (const auto &rel : subset) {
            const std::string abs = corpusRoot + "/" + rel;
            if (!fs::exists(abs)) continue;

            // Construct golden path: <canonGoldDir>/<rel-stem>Canonical.xml
            const std::string goldenPath = canonGoldDir + "/" + rel.substr(0, rel.size() - 4) + "Canonical.xml";
            if (!fs::exists(goldenPath)) continue;

            std::string ours;
            try {
                ours = canonicalize(abs);
            } catch (...) { continue; }

            std::string golden;
            try {
                golden = readFile(goldenPath);
            } catch (...) { continue; }

            ++t2total;

            // Tier 3: byte-exact.
            if (ours == golden) {
                ++t3exact;
                ++t2pass;
                currentState["canon-t2:" + rel] = "PASS";
                continue;
            }

            // Tier 2: tolerant diff.
            auto [agree, reason] = tolerantDiff(golden, ours);
            if (agree) {
                ++t2pass;
                currentState["canon-t2:" + rel] = "PASS";
            } else {
                t2failures.push_back({rel, reason});
                currentState["canon-t2:" + rel] = "FAIL";
            }
        }

        double t2rate = t2total > 0 ? 100.0 * t2pass / t2total : 0.0;
        double t3rate = t2total > 0 ? 100.0 * t3exact / t2total : 0.0;

        std::cout << "  Files with goldens: " << t2total << "\n";
        std::cout << "  TIER 2 tolerant-diff agreement: " << t2pass << "/" << t2total
                  << " (" << static_cast<int>(t2rate + 0.5) << "%)\n";
        std::cout << "  TIER 3 byte-exact:              " << t3exact << "/" << t2total
                  << " (" << static_cast<int>(t3rate + 0.5) << "%)\n";

        if (!t2failures.empty()) {
            std::cout << "\n  Tolerant-diff failures (up to 10):\n";
            for (std::size_t i = 0; i < std::min(t2failures.size(), std::size_t(10)); ++i) {
                std::cout << "    - " << t2failures[i].first
                          << "\n      reason: " << t2failures[i].second << "\n";
            }
        }
        std::cout << "\n";
    }

    // ── Summary ───────────────────────────────────────────────────────────────
    std::cout << "=== SUMMARY ===\n";
    std::cout << "TIER 1 idempotence: " << t1pass << "/" << t1total
              << " (" << static_cast<int>(t1total > 0 ? 100.0 * t1pass / t1total + 0.5 : 0) << "%)"
              << (t1fail > 0 ? " *** FAILURES ***" : " (OK)") << "\n";
    if (!goldensExist) {
        std::cout << "TIER 2/3: *** NOT RUN (0 checks) *** — no local canonical goldens; "
                     "coverage is T1-only. Enable: mise run canon-golden-gen\n";
    }
    std::cout << "\n";

    // ── Write baseline mode ───────────────────────────────────────────────────
    if (writeBaselineMode) {
        writeBaseline(baselinePath, currentState, t1pass, t1total, t2pass, t2total);
        std::cout << "Baseline written: " << baselinePath
                  << " (" << currentState.size() << " entries)\n";
        return (t1fail > 0) ? 1 : 0; // still fail if T1 broken even in write mode
    }

    // ── Gate mode: regression check ──────────────────────────────────────────
    if (gateMode) {
        // A gate that cannot find its inputs must NOT green. If every subset file
        // was skipped (e.g. the corpus dir is absent), currentState is empty —
        // refuse to pass rather than silently report "no regressions".
        if (currentState.empty()) {
            std::cerr << "ERROR: canon gate ran 0 checks — no corpus files found. "
                         "Refusing to pass (a gate with no inputs must not green).\n";
            return 1;
        }
        std::vector<std::string> regressions;
        std::vector<std::string> improvements;

        // Tier 1 is a HARD gate: ANY failure is a regression (100% required).
        // In addition, check per-item against baseline.
        for (const auto &[key, curVal] : currentState) {
            auto it = baseline.find(key);
            if (it == baseline.end()) continue;
            const std::string &baseVal = it->second;
            if (baseVal == "PASS" && curVal == "FAIL") regressions.push_back(key);
            else if (baseVal == "FAIL" && curVal == "PASS") improvements.push_back(key);
        }

        // Also report any T1 failure that wasn't in baseline (new file that now breaks).
        // But since T1 is a hard 100% gate, add any T1 failure to regressions
        // regardless of baseline presence.
        for (const auto &rel : t1failures) {
            std::string key = "canon-t1:" + rel;
            auto it = baseline.find(key);
            // Only add if not already in regressions (would have been caught above)
            if (it == baseline.end() || it->second == "PASS") {
                // Already in regressions list if was PASS. If missing from baseline
                // entirely, it's a new entry that's broken — also a regression.
                bool already = false;
                for (const auto &r : regressions) if (r == key) { already = true; break; }
                if (!already) regressions.push_back(key);
            }
        }

        std::sort(regressions.begin(), regressions.end());
        std::sort(improvements.begin(), improvements.end());

        std::cout << "=== REGRESSION GATE ===\n";
        // Tier 1 hard check.
        if (t1fail > 0) {
            std::cout << "FAIL — Tier-1 idempotence failures (HARD gate, 100% required):\n";
            for (const auto &r : t1failures)
                std::cout << "  REGRESSION(T1): " << r << "\n";
        }
        if (!regressions.empty()) {
            std::cout << "FAIL — " << regressions.size() << " regression(s) detected:\n";
            for (const auto &k : regressions)
                std::cout << "  REGRESSION: " << k << "\n";
        }
        if (t1fail == 0 && regressions.empty())
            std::cout << "PASS — no regressions (Tier-1 100%; all baseline-PASS items still pass"
                      << (goldensExist ? "; tier-2/3 executed" : "; TIER-2/3 NOT RUN — T1-only coverage")
                      << ").\n";

        if (!improvements.empty()) {
            std::cout << "\nNOTE: " << improvements.size() << " improvement(s) detected"
                         " (baseline-FAIL now passes):\n";
            for (const auto &k : improvements)
                std::cout << "  IMPROVED: " << k << "\n";
            std::cout << "  -> Refresh baseline with: mise run cli-gate-baseline\n";
        }

        return (t1fail > 0 || !regressions.empty()) ? 1 : 0;
    }

    // Default informative mode: exit non-zero only if tier-1 fails.
    return (t1fail > 0) ? 1 : 0;
}
