#!/usr/bin/env python3
"""Generate the X3D node->component and profile->component-level tables for the
`x3d validate` profile-fit check, DERIVED FROM THE UOM (the single source of truth).

The UOM gives:
  * node -> (component, level)   via <componentInfo name level> on each <ConcreteNode>
  * profile -> allowed node list via the prose `appinfo` on each profile enumeration

A profile's (component -> maxLevel) table is then DERIVED as the max componentLevel
over the profile's allowed nodes (Full = max over every concrete node). This is the
same relation the X3D spec uses; hand-transcribing it (the old approach) is what let
the tables drift from the spec.

Emits two golden-tracked include fragments consumed by tools/x3d_cli.cpp:
  tools/x3d-cli/node_component_table.gen.inc
  tools/x3d-cli/profile_defs.gen.inc

Usage:  python scripts/gen_profile_tables.py [OUT_DIR]   (default: tools/x3d-cli)
"""
import os
import re
import sys
import xml.etree.ElementTree as ET
from importlib.resources import files

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UOM = str(files("x3d_cpp_gen").joinpath("data", "X3dUnifiedObjectModel-4.0.xml"))

# Profiles modelled by `x3d validate` (must match sdk::Profile, smallest -> largest).
PROFILE_ORDER = ["Core", "Interchange", "CADInterchange", "Interactive",
                 "Immersive", "MedicalInterchange", "Full"]

# The UOM profile prose uses a few stale X3D-3.x node names. Map them to their 4.0
# concrete equivalent so the (informative) interchange profiles don't under-cover;
# anything unmapped is reported as a warning so future UOM drift stays visible.
RENAMES = {
    "CompositeTexture3D":   "ComposedTexture3D",
    "TextureMatrixTransform": "TextureTransformMatrix3D",
    "IndexedTriangleFan":   "IndexedTriangleFanSet",
}
SKIP = {"OctTree"}  # removed in X3D 4.0
# 3.x shader nodes (no 1:1 4.0 concrete node) -> the Shaders component at level 1.
SHADER_NODES = {"FragmentShader", "VertexShader", "Shader", "MultiShader", "ShaderAppearance"}

PROSE = "Allowed X3D nodes for this profile are:"


def node_component_map():
    """node name -> (component, level) from <componentInfo> on each ConcreteNode."""
    root = ET.parse(UOM).getroot()
    m = {}
    for cn in root.iter("ConcreteNode"):
        ci = cn.find(".//componentInfo")
        if ci is not None and ci.get("name"):
            m[cn.get("name")] = (ci.get("name"), int(ci.get("level") or 1))
    m["ProtoInstance"] = ("Core", 2)  # statement-ish node, not in the concrete list
    return m


def profile_node_lists():
    """profile name -> [allowed node names] from the enumeration appinfo prose."""
    xml = open(UOM, encoding="utf-8", errors="replace").read()
    out = {}
    for m in re.finditer(r'<enumeration\s+value="([^"]+)"([^>]*)>', xml, re.S):
        name, attrs = m.group(1), m.group(2)
        am = re.search(re.escape(PROSE) + r"\s*(.*?)\.?\"", attrs, re.S)
        if am and name not in out:
            out[name] = [t for t in re.split(r"\s+", am.group(1).strip()) if t]
    return out


def derive(nodes, node_comp, warnings, profile):
    comp = {}
    for n in nodes:
        if n in SKIP:
            continue
        if n in SHADER_NODES:
            c, l = "Shaders", 1
        else:
            nn = RENAMES.get(n, n)
            if nn not in node_comp:
                warnings.append(f"{profile}: prose node '{n}' not in UOM concrete map")
                continue
            c, l = node_comp[nn]
        comp[c] = max(comp.get(c, 0), l)
    return comp


def build():
    node_comp = node_component_map()
    prose = profile_node_lists()
    warnings = []
    profiles = {}
    for p in PROFILE_ORDER:
        if p == "Full":
            comp = {}
            for c, l in node_comp.values():
                comp[c] = max(comp.get(c, 0), l)
        elif p in prose:
            comp = derive(prose[p], node_comp, warnings, p)
        else:
            warnings.append(f"{p}: no node-list in UOM prose; falling back to {{Core:1}}")
            comp = {"Core": 1}
        profiles[p] = comp
    return node_comp, profiles, warnings


def emit_nodes(node_comp):
    lines = ["// GENERATED by scripts/gen_profile_tables.py from the UOM. DO NOT EDIT.",
             "// node name -> (component, level), from <componentInfo> in the UOM.",
             "// clang-format off"]
    for name in sorted(node_comp):
        c, l = node_comp[name]
        lines.append('{"%s", {"%s", %d}},' % (name, c, l))
    lines.append("// clang-format on")
    return "\n".join(lines) + "\n"


def emit_profiles(profiles):
    lines = ["// GENERATED by scripts/gen_profile_tables.py from the UOM. DO NOT EDIT.",
             "// profile -> (component -> max allowed level), derived from the UOM",
             "// profile node-lists x <componentInfo>. Ordered smallest -> largest.",
             "// clang-format off"]
    for p in PROFILE_ORDER:
        comp = profiles[p]
        pairs = ", ".join('{"%s", %d}' % (c, comp[c]) for c in sorted(comp))
        lines.append("{sdk::Profile::%s, \"%s\", {%s}}," % (p, p, pairs))
    lines.append("// clang-format on")
    return "\n".join(lines) + "\n"


def main():
    out_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(REPO, "tools", "x3d-cli")
    node_comp, profiles, warnings = build()
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "node_component_table.gen.inc"), "w") as f:
        f.write(emit_nodes(node_comp))
    with open(os.path.join(out_dir, "profile_defs.gen.inc"), "w") as f:
        f.write(emit_profiles(profiles))
    print(f"wrote node_component_table.gen.inc ({len(node_comp)} nodes) "
          f"and profile_defs.gen.inc ({len(profiles)} profiles) to {out_dir}")
    for w in warnings:
        print("  warning:", w)
    # Show the derived primary profiles for eyeballing.
    for p in ("Interchange", "Interactive", "Immersive"):
        print(f"  {p}: " + ", ".join(f"{c}:{profiles[p][c]}" for c in sorted(profiles[p])))


if __name__ == "__main__":
    main()
