# cmake/x3d/tests.cmake — behavior and compile-contract test suites (X3D_CPP_BUILD_TESTS).
# Included in order from the top-level CMakeLists.txt (include(), so it shares
# the top-level scope and CMAKE_CURRENT_SOURCE_DIR is the repository root).

if(X3D_CPP_BUILD_TESTS)
    enable_testing()

    set(X3D_CPP_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}/generated_cpp_bindings")

    # Collect all generated headers. CONFIGURE_DEPENDS re-globs on rebuild if
    # the set of headers changes.
    file(GLOB_RECURSE X3D_CPP_HEADERS CONFIGURE_DEPENDS
        "${X3D_CPP_HEADER_DIR}/x3d/*.hpp")
    list(LENGTH X3D_CPP_HEADERS X3D_CPP_HEADER_COUNT)
    message(STATUS "x3d_cpp: found ${X3D_CPP_HEADER_COUNT} generated headers to compile-test")

    # Hand-written runtime document-model headers (X3DDocument, Scene, Route,
    # PROTO, IMPORT/EXPORT). Compiled alongside the generated headers to prove
    # the document model stays consistent with the generated node bindings.
    set(X3D_CPP_RUNTIME_DIR "${CMAKE_CURRENT_SOURCE_DIR}/runtime")
    file(GLOB X3D_CPP_RUNTIME_HEADERS CONFIGURE_DEPENDS "${X3D_CPP_RUNTIME_DIR}/*.hpp")
    list(LENGTH X3D_CPP_RUNTIME_HEADERS X3D_CPP_RUNTIME_HEADER_COUNT)
    message(STATUS "x3d_cpp: found ${X3D_CPP_RUNTIME_HEADER_COUNT} runtime headers to compile-test")

    # Hand-written node-agnostic codecs (XML reader/writer, JSON/VRML writers)
    # plus the bundled XmlLite. Compiled in isolation like the runtime headers.
    set(X3D_CPP_CODEC_DIR "${CMAKE_CURRENT_SOURCE_DIR}/runtime/codecs")
    file(GLOB X3D_CPP_CODEC_HEADERS CONFIGURE_DEPENDS "${X3D_CPP_CODEC_DIR}/*.hpp")
    list(LENGTH X3D_CPP_CODEC_HEADERS X3D_CPP_CODEC_HEADER_COUNT)
    message(STATUS "x3d_cpp: found ${X3D_CPP_CODEC_HEADER_COUNT} codec headers to compile-test")

    # Hand-written event-system runtime (cascade engine, field address, event
    # graph, execution context, active-node protocol, and reference behaviors).
    set(X3D_CPP_EVENT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/runtime/events")
    file(GLOB X3D_CPP_EVENT_HEADERS CONFIGURE_DEPENDS "${X3D_CPP_EVENT_DIR}/*.hpp")
    list(LENGTH X3D_CPP_EVENT_HEADERS X3D_CPP_EVENT_HEADER_COUNT)
    message(STATUS "x3d_cpp: found ${X3D_CPP_EVENT_HEADER_COUNT} event-system headers to compile-test")

    # Hand-written unified parsing front-end (X3DReader interface, encoding
    # sniffing, shared NodeBuilder + VrmlTokenizer, XmlReaderAdapter, X3DParse
    # front door). Compiled in isolation like the codecs/events headers.
    set(X3D_CPP_PARSE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse")
    file(GLOB X3D_CPP_PARSE_HEADERS CONFIGURE_DEPENDS "${X3D_CPP_PARSE_DIR}/*.hpp")
    list(LENGTH X3D_CPP_PARSE_HEADERS X3D_CPP_PARSE_HEADER_COUNT)
    message(STATUS "x3d_cpp: found ${X3D_CPP_PARSE_HEADER_COUNT} parse front-end headers to compile-test")

    # (1) Aggregate target: one .cpp that #includes all generated headers plus
    #     the runtime umbrella and builds it. This proves the whole set is
    #     mutually consistent in one TU.
    set(X3D_CPP_ALL_HEADERS_CPP "${CMAKE_CURRENT_BINARY_DIR}/x3d_cpp_all_headers.cpp")
    set(_x3d_all_content "// Auto-generated by CMake. Includes every generated header.\n")
    foreach(_hdr IN LISTS X3D_CPP_HEADERS)
        file(RELATIVE_PATH _hdr_rel "${X3D_CPP_HEADER_DIR}" "${_hdr}")
        string(APPEND _x3d_all_content "#include \"${_hdr_rel}\"\n")
    endforeach()
    # Pull in the full runtime document model + the node-agnostic codecs on top
    # of the generated nodes.
    string(APPEND _x3d_all_content "#include \"X3DRuntime.hpp\"\n")
    string(APPEND _x3d_all_content "#include \"X3DCodecs.hpp\"\n")
    # Pull in the unified parsing front-end umbrella so it is proven consistent
    # with the generated nodes + codecs in the same TU.
    string(APPEND _x3d_all_content "#include \"X3DParse.hpp\"\n")
    # Pull in the event-system runtime (cascade engine, execution context,
    # reference behaviors) so it is proven consistent in the same TU too.
    foreach(_hdr IN LISTS X3D_CPP_EVENT_HEADERS)
        get_filename_component(_hdr_name "${_hdr}" NAME)
        string(APPEND _x3d_all_content "#include \"${_hdr_name}\"\n")
    endforeach()
    string(APPEND _x3d_all_content "int main() { return 0; }\n")
    file(GENERATE OUTPUT "${X3D_CPP_ALL_HEADERS_CPP}" CONTENT "${_x3d_all_content}")

    add_executable(x3d_cpp_all_headers "${X3D_CPP_ALL_HEADERS_CPP}")
    target_link_libraries(x3d_cpp_all_headers PRIVATE x3d_cpp::headers)
    add_test(NAME x3d_cpp_all_headers COMMAND x3d_cpp_all_headers)

    # (2) Header-isolation contract. Keep one generated translation unit per
    #     public header so diagnostics remain pinned to the exact include, but
    #     put all of those sources in one OBJECT library. This removes hundreds
    #     of CMake/Ninja/CTest targets without weakening header self-containment.
    if(X3D_CPP_PER_HEADER_CHECKS)
        set(X3D_CPP_HEADER_ISOLATION_SOURCES)

        function(_x3d_add_header_isolation_source group include_root header)
            file(RELATIVE_PATH _header_include "${include_root}" "${header}")
            string(REGEX REPLACE
                "[^A-Za-z0-9_]" "_" _source_name "${_header_include}")
            set(_source_dir
                "${CMAKE_CURRENT_BINARY_DIR}/header_isolation/${group}")
            file(MAKE_DIRECTORY "${_source_dir}")
            set(_source "${_source_dir}/${_source_name}.cpp")
            file(GENERATE OUTPUT "${_source}"
                CONTENT "#include \"${_header_include}\"\n")
            set(X3D_CPP_HEADER_ISOLATION_SOURCES
                ${X3D_CPP_HEADER_ISOLATION_SOURCES} "${_source}"
                PARENT_SCOPE)
        endfunction()

        foreach(_hdr IN LISTS X3D_CPP_HEADERS)
            _x3d_add_header_isolation_source(
                generated "${X3D_CPP_HEADER_DIR}" "${_hdr}")
        endforeach()
        foreach(_hdr IN LISTS X3D_CPP_RUNTIME_HEADERS)
            _x3d_add_header_isolation_source(
                runtime "${X3D_CPP_RUNTIME_DIR}" "${_hdr}")
        endforeach()
        foreach(_hdr IN LISTS X3D_CPP_CODEC_HEADERS)
            _x3d_add_header_isolation_source(
                codecs "${X3D_CPP_CODEC_DIR}" "${_hdr}")
        endforeach()
        foreach(_hdr IN LISTS X3D_CPP_EVENT_HEADERS)
            _x3d_add_header_isolation_source(
                events "${X3D_CPP_EVENT_DIR}" "${_hdr}")
        endforeach()
        foreach(_hdr IN LISTS X3D_CPP_PARSE_HEADERS)
            _x3d_add_header_isolation_source(
                parse "${X3D_CPP_PARSE_DIR}" "${_hdr}")
        endforeach()

        add_library(x3d_header_isolation OBJECT EXCLUDE_FROM_ALL
            ${X3D_CPP_HEADER_ISOLATION_SOURCES})
        x3d_set_target_purpose(x3d_header_isolation compile-contract)
        target_link_libraries(x3d_header_isolation PRIVATE x3d_cpp::headers)
        add_test(NAME x3d_header_isolation
            COMMAND "${CMAKE_COMMAND}" --build "${CMAKE_BINARY_DIR}"
                    --target x3d_header_isolation --config "$<CONFIG>")
    endif()

    # AUD-RTC: comprehensive codec round-trip audit via fixture files (Unit 17).
    add_executable(x3d_codec_roundtrip_audit
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/codecs/tests/codec_roundtrip_audit_test.cpp")
    target_link_libraries(x3d_codec_roundtrip_audit PRIVATE x3d_cpp::x3d_cpp)
    add_test(NAME x3d_codec_roundtrip_audit
        COMMAND x3d_codec_roundtrip_audit
            "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/data/proto"
            "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/data/json"
            "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/data/x3dv"
            "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/data/wrl")

    # ------------------------------------------------------------------------
    # S1 dynamic-field foundation (file-authored Script un-tabling, Phase 0).
    # ------------------------------------------------------------------------
    # Phase-0 unit test: AuthorFieldDecl/DynamicFieldStore round-trip,
    # effectiveFields() concatenation, and an author-field ROUTE wiring +
    # delivering end-to-end through X3DSceneBridge.

    # Script / shader author-field capture, one test per reader. Reader tests
    # take their source-tree fixture dir as argv[1]; the end-to-end runtime test
    # links the EcmaScript backend and is registered with it, below.
    #   A. XML capture
    add_executable(x3d_xml_script_field
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/codecs/tests/xml_script_field_test.cpp")
    target_link_libraries(x3d_xml_script_field PRIVATE x3d_cpp::x3d_cpp)
    add_test(NAME x3d_xml_script_field
        COMMAND x3d_xml_script_field
                "${CMAKE_CURRENT_SOURCE_DIR}/runtime/codecs/tests/data")
    #   A'. XML ComposedShader capture (author <field>s + ShaderPart source)
    add_executable(x3d_xml_composed_shader
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/codecs/tests/xml_composed_shader_test.cpp")
    target_link_libraries(x3d_xml_composed_shader PRIVATE x3d_cpp::x3d_cpp)
    add_test(NAME x3d_xml_composed_shader COMMAND x3d_xml_composed_shader)
    #   B. ClassicVRML / VRML97 capture
    add_executable(x3d_vrml_script_field
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/vrml_script_field_test.cpp")
    target_link_libraries(x3d_vrml_script_field PRIVATE x3d_cpp::x3d_cpp)
    add_test(NAME x3d_vrml_script_field
        COMMAND x3d_vrml_script_field
                "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/data")
    #   C. JSON capture
    add_executable(x3d_json_script_field
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/json_script_field_test.cpp")
    target_link_libraries(x3d_json_script_field PRIVATE x3d_cpp::x3d_cpp)
    add_test(NAME x3d_json_script_field
        COMMAND x3d_json_script_field
                "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/data")

    # §37 contact reporting: ContactReporter translates resolved collisions into
    # CollisionSensor.contacts/intersections/isActive events (CONF-RBP). Ungated —
    # the reporter is engine-free; only the Jolt drain path needs the physics flag.
    add_executable(x3d_contact_reporter
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/physics/tests/contact_reporter_test.cpp")
    target_link_libraries(x3d_contact_reporter PRIVATE x3d_cpp::x3d_cpp)
    target_include_directories(x3d_contact_reporter PRIVATE
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/physics")
    add_test(NAME x3d_contact_reporter COMMAND x3d_contact_reporter)

    # PhysicsSystem contact wiring: drain -> resolve handles -> ContactReporter.
    # Ungated (a fake backend scripts a contact); proves the engine-free wiring.
    add_executable(x3d_physics_contact_wiring
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/physics/tests/physics_contact_wiring_test.cpp")
    target_link_libraries(x3d_physics_contact_wiring PRIVATE x3d_cpp::x3d_cpp)
    target_include_directories(x3d_physics_contact_wiring PRIVATE
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/physics")
    add_test(NAME x3d_physics_contact_wiring COMMAND x3d_physics_contact_wiring)

    # §37 inertia/centerOfMass: MassProperties seam + PhysicsSystem detection.
    # Ungated — the detection is engine-free; only the Jolt mapping needs the flag.
    add_executable(x3d_inertia_massprops
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/physics/tests/inertia_massprops_test.cpp")
    target_link_libraries(x3d_inertia_massprops PRIVATE x3d_cpp::x3d_cpp)
    target_include_directories(x3d_inertia_massprops PRIVATE
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/physics")
    add_test(NAME x3d_inertia_massprops COMMAND x3d_inertia_massprops)

    # §37 contact-response params: PhysicsSystem reads CollisionCollection
    # frictionCoefficients/bounce and forwards them to setContactResponse with
    # non-default detection. Ungated — engine-free; uses a recording fake backend.
    add_executable(x3d_contact_response
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/physics/tests/contact_response_test.cpp")
    target_link_libraries(x3d_contact_response PRIVATE x3d_cpp::x3d_cpp)
    target_include_directories(x3d_contact_response PRIVATE
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/physics")
    add_test(NAME x3d_contact_response COMMAND x3d_contact_response)

    #     - scene_bridge_test: the Scene -> EventGraph bridge. Validates ROUTE
    #       resolution (DEF names -> FieldAddress) and rejection of unknown-field
    #       / wrong-direction / type-mismatch routes (dangling DEFs skipped), then
    #       parses a .x3dv document with ROUTEs, bridges it via buildFrom, attaches
    #       the reference behaviors to the DEF-resolved nodes, and ticks the clock
    #       end-to-end. The .x3dv fixtures dir is passed as argv[1] so the test
    #       runs from any working directory.
    add_executable(x3d_event_scene_bridge
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/events/tests/scene_bridge_test.cpp")
    target_link_libraries(x3d_event_scene_bridge PRIVATE x3d_cpp::x3d_cpp)
    add_test(NAME x3d_event_scene_bridge
        COMMAND x3d_event_scene_bridge
                "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/data/x3dv")

    #     - sai_context_test: M4 Track-A unit. The language-agnostic Script
    #       runtime foundation (runtime/script/): the ScriptEngine seam +
    #       in-process SaiContext + a recording MockScriptEngine backend — NO
    #       JavaScript. Asserts field get/set round-trips, the directOutput
    #       write-gate (cross-node write rejected when FALSE, allowed via the
    #       cascade when TRUE), addRoute/deleteRoute gating + effect in the
    #       graph, browser-info getters, and seam-call lifecycle ordering.
    add_executable(x3d_sai_context
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/script/tests/sai_context_test.cpp")
    target_link_libraries(x3d_sai_context PRIVATE x3d_cpp::x3d_cpp)
    add_test(NAME x3d_sai_context COMMAND x3d_sai_context)

    #     - script_system_test: M4 Track-A unit. ScriptSystem — the System that
    #       wires Script lifecycle (load/initialize/shutdown) + event delivery
    #       (inputOnly -> engine.invoke, prepareEvents/eventsProcessed phasing,
    #       outputOnly -> cascade) into the tick/cascade, mock-tested (NO JS).
    #       Asserts the §29.2 ordering: initialize before first event;
    #       prepareEvents before routes; outputOnly at the triggering timestamp;
    #       eventsProcessed once per batch; set_url reload; directOutput gate;
    #       mustEvaluate eager-vs-lazy delivery.
    add_executable(x3d_script_system
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/script/tests/script_system_test.cpp")
    target_link_libraries(x3d_script_system PRIVATE x3d_cpp::x3d_cpp)
    add_test(NAME x3d_script_system COMMAND x3d_script_system)

    # ---------------------------------------------------------------------------
    # M4 Track-B: Duktape ECMAScript backend tests. The backend itself
    # (x3d_duktape / x3d_ecmascript_backend) is defined above, independent of
    # X3D_CPP_BUILD_TESTS, behind X3D_CPP_BUILD_SCRIPT (ON by default) — see
    # that option's block. These test executables still need the test build
    # AND the backend target to exist, hence the nested TARGET guard: a
    # -DX3D_CPP_BUILD_SCRIPT=OFF -DX3D_CPP_BUILD_TESTS=ON configuration builds
    # everything else but skips these.
    # ---------------------------------------------------------------------------
    if(TARGET x3d_ecmascript_backend)
        #     - ecmascript_backend_test: M4 Track-B unit. Proves the full backend:
        #       field marshalling std::any<->JS (all core SF/MF types), the Browser
        #       global object (getName/getVersion/currentTime/addRoute/print backed
        #       by SaiContext), handler dispatch with (value, timestamp), an
        #       end-to-end ROUTE wired by the script via Browser.addRoute, and the
        #       directOutput gate throwing into JS.
        add_executable(x3d_ecmascript_backend_test
            "${CMAKE_CURRENT_SOURCE_DIR}/runtime/script/tests/ecmascript_backend_test.cpp")
        target_link_libraries(x3d_ecmascript_backend_test PRIVATE
            x3d_ecmascript_backend)
        add_test(NAME x3d_ecmascript_backend COMMAND x3d_ecmascript_backend_test)

        #     - ecmascript_corpus_smoke_test: M4 Track-B corpus smoke. Drives
        #       parse -> expand -> attach ScriptSystem(EcmaScriptBackend) -> tick on
        #       an authored known scene (deterministic Browser.print) and a few real
        #       Script-bearing .x3d from testdata (no-crash robustness).
        add_executable(x3d_ecmascript_corpus_smoke_test
            "${CMAKE_CURRENT_SOURCE_DIR}/runtime/script/tests/ecmascript_corpus_smoke_test.cpp")
        target_link_libraries(x3d_ecmascript_corpus_smoke_test PRIVATE
            x3d_ecmascript_backend)
        add_test(NAME x3d_ecmascript_corpus_smoke
            COMMAND x3d_ecmascript_corpus_smoke_test)

        #   D. Runtime wiring: source-from-sourceCode, author-event dispatch,
        #      author-field marshalling + an end-to-end "author field drives a
        #      ROUTE" test, through the real EcmaScript backend.
        add_executable(x3d_script_author_runtime
            "${CMAKE_CURRENT_SOURCE_DIR}/runtime/script/tests/script_author_runtime_test.cpp")
        target_link_libraries(x3d_script_author_runtime PRIVATE
            x3d_ecmascript_backend)
        add_test(NAME x3d_script_author_runtime COMMAND x3d_script_author_runtime)

        #   Phase-2 CORPUS END-TO-END proof: a FILE-AUTHORED Script that v1 shipped
        #   INERT now actually executes through the real reader -> expand -> attach ->
        #   tick path (XML: the Savage CanopyExample.x3d; ClassicVRML: an authored
        #   .x3dv fixture). Closes SCR-SAI-DYN (S1) behaviorally. The data dir arg
        #   locates the .x3dv fixture; the .x3d is the absolute corpus path.
        add_executable(x3d_script_corpus_e2e
            "${CMAKE_CURRENT_SOURCE_DIR}/runtime/script/tests/script_corpus_e2e_test.cpp")
        target_link_libraries(x3d_script_corpus_e2e PRIVATE
            x3d_ecmascript_backend)
        add_test(NAME x3d_script_corpus_e2e
            COMMAND x3d_script_corpus_e2e
                    "${CMAKE_CURRENT_SOURCE_DIR}/runtime/script/tests/data")
    endif()

    # (4) Parse front-end integration test (WS-A), built and RUN (not just
    #     compiled): encoding sniffing (extension + content + override + gzip),
    #     the shared VrmlTokenizer, NodeBuilder::collectFieldValue value
    #     round-trips, and the XmlReaderAdapter / parseDocument front door
    #     reproducing the raw XmlReader.
    #     Fix 1 (parser-gap plan) adds testGzipInflate(): the data dir is passed
    #     as argv[1] so parseFile() can round-trip the committed gzip fixtures
    #     (runtime/parse/tests/data/gzip/) against their uncompressed siblings.
    add_executable(x3d_parse_reader
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/reader_test.cpp")
    target_link_libraries(x3d_parse_reader PRIVATE x3d_cpp::x3d_cpp)
    add_test(NAME x3d_parse_reader
        COMMAND x3d_parse_reader
                "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/data")

    # (10) ClassicVRML (.x3dv) reader test (WS-B), built and RUN. Parses the four
    #      corpus .x3dv fixtures (copied into runtime/parse/tests/data/x3dv/) plus
    #      hand-authored grammar snippets into a Scene and asserts node types,
    #      field values, DEF/USE shared identity, ROUTEs, header statements, MF
    #      re-join, and PROTO/EXTERNPROTO/instance/IS capture. The fixtures dir is
    #      passed as argv[1] so the test runs from any working directory.
    add_executable(x3d_classic_vrml_reader
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/classic_vrml_reader_test.cpp")
    target_link_libraries(x3d_classic_vrml_reader PRIVATE x3d_cpp::x3d_cpp)
    add_test(NAME x3d_classic_vrml_reader
        COMMAND x3d_classic_vrml_reader
                "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/data/x3dv")

    # Front-door PROTO expansion (Task 10): parseDocument/parseFile drive
    # expandScene with the default local-file resolver. Asserts local-PROTO
    # in-memory expansion, sibling-file EXTERNPROTO resolution (baseUrl derived
    # from the file path), and termination of a mutually-referential EXTERN
    # cycle. The fixtures dir is passed as argv[1] so it runs from any cwd.
    add_executable(x3d_proto_front_door
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/proto_front_door_test.cpp")
    target_link_libraries(x3d_proto_front_door PRIVATE x3d_cpp::x3d_cpp)
    add_test(NAME x3d_proto_front_door
        COMMAND x3d_proto_front_door
                "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/data/proto")

    # AUD-PROTO-EXP regression: PROTO expansion + IS routing + depth guard +
    # redirect-validation. The fixtures dir is passed as argv[1] so the test
    # runs from any cwd (default: runtime/parse/tests/data/proto).
    add_executable(x3d_proto_expand_audit
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/proto_expand_audit_test.cpp")
    target_link_libraries(x3d_proto_expand_audit PRIVATE x3d_cpp::x3d_cpp)
    add_test(NAME x3d_proto_expand_audit
        COMMAND x3d_proto_expand_audit
                "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/data/proto")

    # Task 3 (Inline round-trip): writer redirect — re-emit <Inline url=.../>
    # via expandedInlines and do NOT serialize the synthetic Group's child content.
    add_executable(x3d_inline_roundtrip
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/inline_roundtrip_test.cpp")
    target_link_libraries(x3d_inline_roundtrip PRIVATE x3d_cpp::sdk)
    add_test(NAME x3d_inline_roundtrip
        COMMAND x3d_inline_roundtrip
                "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/data/inline")

    # Task 4 (Inline route hoisting): resolvedInlineRoutes populated by
    # expandInlines and registered on the execution context by the scene-bridge,
    # so self-animating inlined assets tick.
    add_executable(x3d_inline_routes
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/inline_routes_test.cpp")
    target_link_libraries(x3d_inline_routes PRIVATE x3d_cpp::sdk)
    add_test(NAME x3d_inline_routes
        COMMAND x3d_inline_routes
                "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/data/inline")

    add_executable(x3d_inline_cycle
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/inline_cycle_test.cpp")
    target_link_libraries(x3d_inline_cycle PRIVATE x3d_cpp::sdk)
    add_test(NAME x3d_inline_cycle
        COMMAND x3d_inline_cycle
                "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/data/inline")

    # SEC-5: inflateGzip caps decompressed output (gzip decompression-bomb DoS).
    add_executable(x3d_inflate_bomb
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/inflate_bomb_test.cpp")
    target_link_libraries(x3d_inflate_bomb PRIVATE x3d_cpp::sdk)
    add_test(NAME x3d_inflate_bomb COMMAND x3d_inflate_bomb)

    # SEC-3/SEC-4: confineLocalIncludePath rejects path-traversal/absolute reads
    # and de-aliases the cycle-guard key.
    add_executable(x3d_path_confine
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/path_confine_test.cpp")
    target_link_libraries(x3d_path_confine PRIVATE x3d_cpp::sdk)
    add_test(NAME x3d_path_confine COMMAND x3d_path_confine)

    # Regression: expandInlines walk must not stack-overflow on containment cycles
    # (USE-shared or self-referential nodes). Guard mirrors sibling system walkers.
    add_executable(x3d_inline_containment_cycle
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/inline_containment_cycle_test.cpp")
    target_link_libraries(x3d_inline_containment_cycle PRIVATE x3d_cpp::sdk)
    add_test(NAME x3d_inline_containment_cycle
        COMMAND x3d_inline_containment_cycle
                "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/data/inline")

    # (10b) VRML97 (.wrl) reader test (WS-C), built and RUN. Parses the five text
    #       corpus .wrl fixtures (copied into runtime/parse/tests/data/wrl/) plus
    #       hand-authored snippets into a Scene and asserts the VRML97 dialect:
    #       node/field reflection resolution, the dialect rename-table tripwire
    #       (every mapped X3D target must resolve, catching generated-binding
    #       drift), TRUE/FALSE + access-keyword aliases, LOD.level/Switch.choice
    #       -> children, PROTO/Script carry-through, DEF/USE + ROUTE recovery,
    #       VRML 1.0 rejection, the unknown-node/field warning path, and the
    #       parseDocument front-door VRML97 dispatch. The fixtures dir is passed
    #       as argv[1] so the test runs from any working directory.
    add_executable(x3d_vrml97_reader
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/vrml97_reader_test.cpp")
    target_link_libraries(x3d_vrml97_reader PRIVATE x3d_cpp::x3d_cpp)
    add_test(NAME x3d_vrml97_reader
        COMMAND x3d_vrml97_reader
                "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/data/wrl")

    # (11) X3D-JSON (.json) reader test (WS-D), built and RUN. Parses the corpus-
    #      derived .json fixtures (runtime/parse/tests/data/json/, produced from
    #      corpus X3D via the XML/ClassicVRML readers + JsonWriter) plus hand-
    #      authored snippets into a Scene and asserts profile/version, head
    #      metadata, node types + field values, DEF/USE shared identity, ROUTE/
    #      IMPORT/EXPORT recovery, the JsonWriter->JsonReader->JsonWriter byte-
    #      stable round-trip (read/write symmetry), and parseDocument front-door
    #      JSON dispatch. The fixtures dir is passed as argv[1] so the test runs
    #      from any working directory.
    add_executable(x3d_json_reader
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/json_reader_test.cpp")
    target_link_libraries(x3d_json_reader PRIVATE x3d_cpp::x3d_cpp)
    add_test(NAME x3d_json_reader
        COMMAND x3d_json_reader
                "${CMAKE_CURRENT_SOURCE_DIR}/runtime/parse/tests/data/json")

    # T-SDK: the façade surface test. Drives load -> context -> extract -> tick
    # using ONLY x3d::sdk::* names through the single "x3d/sdk.hpp" include, so a
    # dropped/renamed re-export fails to compile here.
    add_executable(x3d_sdk_facade
        "${CMAKE_CURRENT_SOURCE_DIR}/include/x3d/tests/sdk_facade_test.cpp")
    target_link_libraries(x3d_sdk_facade PRIVATE x3d_cpp::sdk)
    add_test(NAME x3d_sdk_facade COMMAND x3d_sdk_facade)
    add_executable(x3d_authoring_link_contract
        "${CMAKE_CURRENT_SOURCE_DIR}/examples/embed_minimal/authoring.cpp")
    target_link_libraries(x3d_authoring_link_contract PRIVATE
        x3d_cpp::authoring)
    add_test(NAME x3d_authoring_link_contract
        COMMAND x3d_authoring_link_contract)
    # Installed-package embed smoke: install THIS build, then configure/build/run
    # examples/embed_minimal against it via find_package(x3d_cpp), so a broken
    # export or a missing installed header fails CI on the actual embedder path.
    # The parent generator is forwarded so the downstream configure matches it.
    #
    # Skipped under X3D_CPP_SAN: the sanitizer build instruments the installed
    # archive globally (add_compile/link_options -fsanitize), but the downstream
    # example builds plain — linking it against the instrumented archive fails
    # with undefined __asan_*/__ubsan_* symbols. Install wiring is orthogonal to
    # sanitizers, so the dev/CI fast gate already proves it.
    if(NOT X3D_CPP_SAN)
        add_test(NAME x3d_install_embed_smoke
            COMMAND bash "${CMAKE_CURRENT_SOURCE_DIR}/scripts/verify_install_embed.sh"
                    "${CMAKE_CURRENT_BINARY_DIR}"
                    "${CMAKE_CURRENT_BINARY_DIR}/install-embed-smoke"
                    "${CMAKE_GENERATOR}")
    endif()

    # Contract: the generated package version file must reject a mismatched
    # pointer size (the package ships compiled .so files, so it is NOT
    # arch-independent) and must not treat a different MINOR as compatible (at
    # 0.x, SameMajorVersion would green-light every future 0.y). Drives the
    # generated file directly, so it needs no cross-compiler.
    add_test(NAME x3d_package_version_contract
        COMMAND "${CMAKE_COMMAND}"
                "-DVERSION_FILE=${CMAKE_CURRENT_BINARY_DIR}/x3d_cppConfigVersion.cmake"
                "-DBUILD_SIZEOF_VOID_P=${CMAKE_SIZEOF_VOID_P}"
                -P "${CMAKE_CURRENT_SOURCE_DIR}/tests/cmake/package_version/check_version_file.cmake")

    # Contract: adding x3d_cpp with add_subdirectory() must not mutate cache or
    # global state that reaches the consumer. Configure-only.
    #
    # -G is REQUIRED: without it the nested configure picks CMake's default
    # (often Unix Makefiles), where the JOB_POOLS property is ignored -- the
    # fixture would then never exercise the global-pool bug and would pass for
    # the wrong reason.
    #
    # -DCCACHE_PROGRAM makes the launcher half hermetic: x3d_cpp guards its cache
    # write behind find_program(CCACHE_PROGRAM ccache), so on a machine without
    # ccache the block is a no-op and the test again passes for the wrong reason.
    # Pre-seeding the find_program cache variable with a known-present executable
    # forces the write to happen. It is never executed (configure-only), so any
    # real path works; /bin/echo is used because it exists everywhere we build.
    add_test(NAME x3d_dev_tooling_isolation
        COMMAND "${CMAKE_COMMAND}"
                -S "${CMAKE_CURRENT_SOURCE_DIR}/tests/cmake/dev_tooling"
                -B "${CMAKE_CURRENT_BINARY_DIR}/dev_tooling_fixture"
                -G "${CMAKE_GENERATOR}"
                "-DCCACHE_PROGRAM=/bin/echo"
                "-DX3D_CPP_SOURCE_DIR=${CMAKE_CURRENT_SOURCE_DIR}")

    # T-SOUND: the §16 Sound seam (runtime/sound/). The AudioBackend seam +
    # SoundSystem are CORE, header-only, DSP-free (mirrors PhysicsBackend +
    # PhysicsSystem). Unlike physics, the default DSP backend has NO external
    # dependency (pure math), so it is always built — no flag gate. The test
    # drives the §16 children-graph in two tiers (recording graph + real DSP
    # samples) plus param-animation + determinism.
    add_executable(x3d_sound_system
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/sound/dsp/BuiltinDspBackend.cpp"
        "${CMAKE_CURRENT_SOURCE_DIR}/runtime/sound/tests/sound_system_test.cpp")
    target_link_libraries(x3d_sound_system PRIVATE x3d_cpp::x3d_cpp)
    add_test(NAME x3d_sound_system COMMAND x3d_sound_system)

    # Author-shader binding plan (vocabulary + introspection).
endif()
